//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.aixm.delorean.core.schema.a5_1_1.org.gml;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.XmlValue;
import org.w3._2001.xmlschema.PositiveInteger;


/**
 * posList instances (and other instances with the content model specified by DirectPositionListType) hold the coordinates for a sequence of direct positions within the same coordinate reference system (CRS).
 * if no srsName attribute is given, the CRS shall be specified as part of the larger context this geometry element is part of, typically a geometric object like a point, curve, etc. 
 * The optional attribute count specifies the number of direct positions in the list. If the attribute count is present then the attribute srsDimension shall be present, too.
 * The number of entries in the list is equal to the product of the dimensionality of the coordinate reference system (i.e. it is a derived value of the coordinate reference system definition) and the number of direct positions.
 * 
 * <p>Java class for DirectPositionListType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="DirectPositionListType">
 *   <simpleContent>
 *     <extension base="<http://www.opengis.net/gml/3.2>doubleList">
 *       <attGroup ref="{http://www.opengis.net/gml/3.2}SRSReferenceGroup"/>
 *       <attribute name="count" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *     </extension>
 *   </simpleContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DirectPositionListType", propOrder = {
    "value"
})
public class DirectPositionListType {

    /**
     * A type for a list of values of the respective simple type.
     * 
     */
    @XmlValue
    protected DoubleList value;
    @XmlAttribute(name = "count")
    protected PositiveInteger count;
    @XmlAttribute(name = "srsName")
    @XmlSchemaType(name = "anyURI")
    protected String srsName;
    @XmlAttribute(name = "srsDimension")
    protected PositiveInteger srsDimension;
    @XmlAttribute(name = "axisLabels")
    protected NCNameList axisLabels;
    @XmlAttribute(name = "uomLabels")
    protected NCNameList uomLabels;

    /**
     * A type for a list of values of the respective simple type.
     * 
     * @return
     *     possible object is
     *     {@link DoubleList }
     *     
     */
    public DoubleList getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link DoubleList }
     *     
     * @see #getValue()
     */
    public void setValue(DoubleList value) {
        this.value = value;
    }

    public boolean isSetValue() {
        return (this.value!= null);
    }

    /**
     * Gets the value of the count property.
     * 
     * @return
     *     possible object is
     *     {@link PositiveInteger }
     *     
     */
    public PositiveInteger getCount() {
        return count;
    }

    /**
     * Sets the value of the count property.
     * 
     * @param value
     *     allowed object is
     *     {@link PositiveInteger }
     *     
     */
    public void setCount(PositiveInteger value) {
        this.count = value;
    }

    public boolean isSetCount() {
        return (this.count!= null);
    }

    /**
     * Gets the value of the srsName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSrsName() {
        return srsName;
    }

    /**
     * Sets the value of the srsName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSrsName(String value) {
        this.srsName = value;
    }

    public boolean isSetSrsName() {
        return (this.srsName!= null);
    }

    /**
     * Gets the value of the srsDimension property.
     * 
     * @return
     *     possible object is
     *     {@link PositiveInteger }
     *     
     */
    public PositiveInteger getSrsDimension() {
        return srsDimension;
    }

    /**
     * Sets the value of the srsDimension property.
     * 
     * @param value
     *     allowed object is
     *     {@link PositiveInteger }
     *     
     */
    public void setSrsDimension(PositiveInteger value) {
        this.srsDimension = value;
    }

    public boolean isSetSrsDimension() {
        return (this.srsDimension!= null);
    }

    /**
     * Gets the value of the axisLabels property.
     * 
     * @return
     *     possible object is
     *     {@link NCNameList }
     *     
     */
    public NCNameList getAxisLabels() {
        return axisLabels;
    }

    /**
     * Sets the value of the axisLabels property.
     * 
     * @param value
     *     allowed object is
     *     {@link NCNameList }
     *     
     */
    public void setAxisLabels(NCNameList value) {
        this.axisLabels = value;
    }

    public boolean isSetAxisLabels() {
        return (this.axisLabels!= null);
    }

    /**
     * Gets the value of the uomLabels property.
     * 
     * @return
     *     possible object is
     *     {@link NCNameList }
     *     
     */
    public NCNameList getUomLabels() {
        return uomLabels;
    }

    /**
     * Sets the value of the uomLabels property.
     * 
     * @param value
     *     allowed object is
     *     {@link NCNameList }
     *     
     */
    public void setUomLabels(NCNameList value) {
        this.uomLabels = value;
    }

    public boolean isSetUomLabels() {
        return (this.uomLabels!= null);
    }

}
