//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.aixm.delorean.core.org.gml;

import java.util.ArrayList;
import java.util.List;
import com.aixm.delorean.core.aixm.AbstractAIXMFeatureType;
import com.aixm.delorean.core.aixm.AbstractAirportGroundServiceType;
import com.aixm.delorean.core.aixm.AbstractAirportHeliportProtectionAreaType;
import com.aixm.delorean.core.aixm.AbstractApproachLegType;
import com.aixm.delorean.core.aixm.AbstractGroundLightSystemType;
import com.aixm.delorean.core.aixm.AbstractMarkingType;
import com.aixm.delorean.core.aixm.AbstractNavaidEquipmentType;
import com.aixm.delorean.core.aixm.AbstractNavigationSystemCheckpointType;
import com.aixm.delorean.core.aixm.AbstractProcedureType;
import com.aixm.delorean.core.aixm.AbstractRadarEquipmentType;
import com.aixm.delorean.core.aixm.AbstractSegmentLegType;
import com.aixm.delorean.core.aixm.AbstractServiceType;
import com.aixm.delorean.core.aixm.AbstractSurveillanceRadarType;
import com.aixm.delorean.core.aixm.AbstractTrafficSeparationServiceType;
import com.aixm.delorean.core.aixm.AerialRefuellingType;
import com.aixm.delorean.core.aixm.AeronauticalGroundLightType;
import com.aixm.delorean.core.aixm.AirTrafficControlServiceType;
import com.aixm.delorean.core.aixm.AirTrafficManagementServiceType;
import com.aixm.delorean.core.aixm.AircraftGroundServiceType;
import com.aixm.delorean.core.aixm.AircraftStandType;
import com.aixm.delorean.core.aixm.AirportClearanceServiceType;
import com.aixm.delorean.core.aixm.AirportHeliportCollocationType;
import com.aixm.delorean.core.aixm.AirportHeliportType;
import com.aixm.delorean.core.aixm.AirportHotSpotType;
import com.aixm.delorean.core.aixm.AirportProtectionAreaMarkingType;
import com.aixm.delorean.core.aixm.AirportSuppliesServiceType;
import com.aixm.delorean.core.aixm.AirspaceBorderCrossingType;
import com.aixm.delorean.core.aixm.AirspaceType;
import com.aixm.delorean.core.aixm.AltimeterSourceType;
import com.aixm.delorean.core.aixm.AngleIndicationType;
import com.aixm.delorean.core.aixm.ApproachLightingSystemType;
import com.aixm.delorean.core.aixm.ApronElementType;
import com.aixm.delorean.core.aixm.ApronLightSystemType;
import com.aixm.delorean.core.aixm.ApronMarkingType;
import com.aixm.delorean.core.aixm.ApronType;
import com.aixm.delorean.core.aixm.ArrestingGearType;
import com.aixm.delorean.core.aixm.ArrivalFeederLegType;
import com.aixm.delorean.core.aixm.ArrivalLegType;
import com.aixm.delorean.core.aixm.AuthorityForAirspaceType;
import com.aixm.delorean.core.aixm.AzimuthType;
import com.aixm.delorean.core.aixm.ChangeOverPointType;
import com.aixm.delorean.core.aixm.CheckpointINSType;
import com.aixm.delorean.core.aixm.CheckpointVORType;
import com.aixm.delorean.core.aixm.CirclingAreaType;
import com.aixm.delorean.core.aixm.DMEType;
import com.aixm.delorean.core.aixm.DeicingAreaMarkingType;
import com.aixm.delorean.core.aixm.DeicingAreaType;
import com.aixm.delorean.core.aixm.DepartureLegType;
import com.aixm.delorean.core.aixm.DesignatedPointType;
import com.aixm.delorean.core.aixm.DirectionFinderType;
import com.aixm.delorean.core.aixm.DistanceIndicationType;
import com.aixm.delorean.core.aixm.ElevationType;
import com.aixm.delorean.core.aixm.FinalLegType;
import com.aixm.delorean.core.aixm.FireFightingServiceType;
import com.aixm.delorean.core.aixm.FlightRestrictionType;
import com.aixm.delorean.core.aixm.FloatingDockSiteType;
import com.aixm.delorean.core.aixm.GeoBorderType;
import com.aixm.delorean.core.aixm.GlidepathType;
import com.aixm.delorean.core.aixm.GroundTrafficControlServiceType;
import com.aixm.delorean.core.aixm.GuidanceLineLightSystemType;
import com.aixm.delorean.core.aixm.GuidanceLineMarkingType;
import com.aixm.delorean.core.aixm.GuidanceLineType;
import com.aixm.delorean.core.aixm.HoldingAssessmentType;
import com.aixm.delorean.core.aixm.HoldingPatternType;
import com.aixm.delorean.core.aixm.InformationServiceType;
import com.aixm.delorean.core.aixm.InitialLegType;
import com.aixm.delorean.core.aixm.InstrumentApproachProcedureType;
import com.aixm.delorean.core.aixm.IntermediateLegType;
import com.aixm.delorean.core.aixm.LocalizerType;
import com.aixm.delorean.core.aixm.MarkerBeaconType;
import com.aixm.delorean.core.aixm.MarkingBuoyType;
import com.aixm.delorean.core.aixm.MissedApproachLegType;
import com.aixm.delorean.core.aixm.NDBType;
import com.aixm.delorean.core.aixm.NavaidType;
import com.aixm.delorean.core.aixm.NavigationAreaRestrictionType;
import com.aixm.delorean.core.aixm.NavigationAreaType;
import com.aixm.delorean.core.aixm.NonMovementAreaType;
import com.aixm.delorean.core.aixm.ObstacleAreaType;
import com.aixm.delorean.core.aixm.OrganisationAuthorityType;
import com.aixm.delorean.core.aixm.PassengerLoadingBridgeType;
import com.aixm.delorean.core.aixm.PassengerServiceType;
import com.aixm.delorean.core.aixm.PilotControlledLightingType;
import com.aixm.delorean.core.aixm.PrecisionApproachRadarType;
import com.aixm.delorean.core.aixm.PrimarySurveillanceRadarType;
import com.aixm.delorean.core.aixm.ProcedureDMEType;
import com.aixm.delorean.core.aixm.RadarSystemType;
import com.aixm.delorean.core.aixm.RadioCommunicationChannelType;
import com.aixm.delorean.core.aixm.RadioFrequencyAreaType;
import com.aixm.delorean.core.aixm.RoadType;
import com.aixm.delorean.core.aixm.RouteDMEType;
import com.aixm.delorean.core.aixm.RouteSegmentType;
import com.aixm.delorean.core.aixm.RouteType;
import com.aixm.delorean.core.aixm.RulesProceduresType;
import com.aixm.delorean.core.aixm.RunwayBlastPadType;
import com.aixm.delorean.core.aixm.RunwayCentrelinePointType;
import com.aixm.delorean.core.aixm.RunwayDirectionLightSystemType;
import com.aixm.delorean.core.aixm.RunwayDirectionType;
import com.aixm.delorean.core.aixm.RunwayElementType;
import com.aixm.delorean.core.aixm.RunwayMarkingType;
import com.aixm.delorean.core.aixm.RunwayProtectAreaLightSystemType;
import com.aixm.delorean.core.aixm.RunwayProtectAreaType;
import com.aixm.delorean.core.aixm.RunwayType;
import com.aixm.delorean.core.aixm.RunwayVisualRangeType;
import com.aixm.delorean.core.aixm.SDFType;
import com.aixm.delorean.core.aixm.SafeAltitudeAreaType;
import com.aixm.delorean.core.aixm.SeaplaneLandingAreaType;
import com.aixm.delorean.core.aixm.SeaplaneRampSiteType;
import com.aixm.delorean.core.aixm.SearchRescueServiceType;
import com.aixm.delorean.core.aixm.SecondarySurveillanceRadarType;
import com.aixm.delorean.core.aixm.SignificantPointInAirspaceType;
import com.aixm.delorean.core.aixm.SpecialDateType;
import com.aixm.delorean.core.aixm.SpecialNavigationStationType;
import com.aixm.delorean.core.aixm.SpecialNavigationSystemType;
import com.aixm.delorean.core.aixm.StandMarkingType;
import com.aixm.delorean.core.aixm.StandardInstrumentArrivalType;
import com.aixm.delorean.core.aixm.StandardInstrumentDepartureType;
import com.aixm.delorean.core.aixm.StandardLevelColumnType;
import com.aixm.delorean.core.aixm.StandardLevelSectorType;
import com.aixm.delorean.core.aixm.StandardLevelTableType;
import com.aixm.delorean.core.aixm.SurveyControlPointType;
import com.aixm.delorean.core.aixm.TACANType;
import com.aixm.delorean.core.aixm.TaxiHoldingPositionLightSystemType;
import com.aixm.delorean.core.aixm.TaxiHoldingPositionMarkingType;
import com.aixm.delorean.core.aixm.TaxiHoldingPositionType;
import com.aixm.delorean.core.aixm.TaxiwayElementType;
import com.aixm.delorean.core.aixm.TaxiwayLightSystemType;
import com.aixm.delorean.core.aixm.TaxiwayMarkingType;
import com.aixm.delorean.core.aixm.TaxiwayType;
import com.aixm.delorean.core.aixm.TerminalArrivalAreaType;
import com.aixm.delorean.core.aixm.TouchDownLiftOffLightSystemType;
import com.aixm.delorean.core.aixm.TouchDownLiftOffMarkingType;
import com.aixm.delorean.core.aixm.TouchDownLiftOffSafeAreaType;
import com.aixm.delorean.core.aixm.TouchDownLiftOffType;
import com.aixm.delorean.core.aixm.UnitType;
import com.aixm.delorean.core.aixm.UnplannedHoldingType;
import com.aixm.delorean.core.aixm.VORType;
import com.aixm.delorean.core.aixm.VerticalStructureType;
import com.aixm.delorean.core.aixm.VisualGlideSlopeIndicatorType;
import com.aixm.delorean.core.aixm.WorkAreaType;
import com.aixm.delorean.core.aixm.message.AIXMBasicMessageType;
import com.aixm.delorean.core.org.w3.xlink.ActuateType;
import com.aixm.delorean.core.org.w3.xlink.ShowType;
import com.aixm.delorean.core.org.w3.xlink.TypeType;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FeaturePropertyType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="FeaturePropertyType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence minOccurs="0">
 *         <element ref="{http://www.opengis.net/gml/3.2}AbstractFeature"/>
 *       </sequence>
 *       <attGroup ref="{http://www.opengis.net/gml/3.2}OwnershipAttributeGroup"/>
 *       <attGroup ref="{http://www.opengis.net/gml/3.2}AssociationAttributeGroup"/>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FeaturePropertyType", propOrder = {
    "abstractFeature"
})
public class FeaturePropertyType {

    /**
     * This abstract element serves as the head of a substitution group which may contain any elements whose content model is derived from gml:AbstractFeatureType.  This may be used as a variable in the construction of content models.  
     * gml:AbstractFeature may be thought of as "anything that is a GML feature" and may be used to define variables or templates in which the value of a GML property is "any feature". This occurs in particular in a GML feature collection where the feature member properties contain one or multiple copies of gml:AbstractFeature respectively.
     * 
     */
    @XmlElementRef(name = "AbstractFeature", namespace = "http://www.opengis.net/gml/3.2", type = JAXBElement.class, required = false)
    protected JAXBElement<? extends AbstractFeatureType> abstractFeature;
    @XmlAttribute(name = "owns")
    protected java.lang.Boolean owns;
    @XmlAttribute(name = "nilReason")
    protected List<String> nilReason;
    @XmlAttribute(name = "remoteSchema", namespace = "http://www.opengis.net/gml/3.2")
    @XmlSchemaType(name = "anyURI")
    protected String remoteSchema;
    @XmlAttribute(name = "type", namespace = "http://www.w3.org/1999/xlink")
    public static final TypeType TYPE = TypeType.SIMPLE;
    @XmlAttribute(name = "href", namespace = "http://www.w3.org/1999/xlink")
    protected String href;
    @XmlAttribute(name = "role", namespace = "http://www.w3.org/1999/xlink")
    protected String role;
    @XmlAttribute(name = "arcrole", namespace = "http://www.w3.org/1999/xlink")
    protected String arcrole;
    @XmlAttribute(name = "title", namespace = "http://www.w3.org/1999/xlink")
    protected String titleAttribute;
    @XmlAttribute(name = "show", namespace = "http://www.w3.org/1999/xlink")
    protected ShowType show;
    @XmlAttribute(name = "actuate", namespace = "http://www.w3.org/1999/xlink")
    protected ActuateType actuate;

    /**
     * This abstract element serves as the head of a substitution group which may contain any elements whose content model is derived from gml:AbstractFeatureType.  This may be used as a variable in the construction of content models.  
     * gml:AbstractFeature may be thought of as "anything that is a GML feature" and may be used to define variables or templates in which the value of a GML property is "any feature". This occurs in particular in a GML feature collection where the feature member properties contain one or multiple copies of gml:AbstractFeature respectively.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link AbstractAIXMFeatureType }{@code >}
     *     {@link JAXBElement }{@code <}{@link AbstractAirportGroundServiceType }{@code >}
     *     {@link JAXBElement }{@code <}{@link AbstractAirportHeliportProtectionAreaType }{@code >}
     *     {@link JAXBElement }{@code <}{@link AbstractApproachLegType }{@code >}
     *     {@link JAXBElement }{@code <}{@link AbstractGroundLightSystemType }{@code >}
     *     {@link JAXBElement }{@code <}{@link AbstractMarkingType }{@code >}
     *     {@link JAXBElement }{@code <}{@link AbstractNavaidEquipmentType }{@code >}
     *     {@link JAXBElement }{@code <}{@link AbstractNavigationSystemCheckpointType }{@code >}
     *     {@link JAXBElement }{@code <}{@link AbstractProcedureType }{@code >}
     *     {@link JAXBElement }{@code <}{@link AbstractRadarEquipmentType }{@code >}
     *     {@link JAXBElement }{@code <}{@link AbstractSegmentLegType }{@code >}
     *     {@link JAXBElement }{@code <}{@link AbstractServiceType }{@code >}
     *     {@link JAXBElement }{@code <}{@link AbstractSurveillanceRadarType }{@code >}
     *     {@link JAXBElement }{@code <}{@link AbstractTrafficSeparationServiceType }{@code >}
     *     {@link JAXBElement }{@code <}{@link AerialRefuellingType }{@code >}
     *     {@link JAXBElement }{@code <}{@link AeronauticalGroundLightType }{@code >}
     *     {@link JAXBElement }{@code <}{@link AirTrafficControlServiceType }{@code >}
     *     {@link JAXBElement }{@code <}{@link AirTrafficManagementServiceType }{@code >}
     *     {@link JAXBElement }{@code <}{@link AircraftGroundServiceType }{@code >}
     *     {@link JAXBElement }{@code <}{@link AircraftStandType }{@code >}
     *     {@link JAXBElement }{@code <}{@link AirportClearanceServiceType }{@code >}
     *     {@link JAXBElement }{@code <}{@link AirportHeliportCollocationType }{@code >}
     *     {@link JAXBElement }{@code <}{@link AirportHeliportType }{@code >}
     *     {@link JAXBElement }{@code <}{@link AirportHotSpotType }{@code >}
     *     {@link JAXBElement }{@code <}{@link AirportProtectionAreaMarkingType }{@code >}
     *     {@link JAXBElement }{@code <}{@link AirportSuppliesServiceType }{@code >}
     *     {@link JAXBElement }{@code <}{@link AirspaceBorderCrossingType }{@code >}
     *     {@link JAXBElement }{@code <}{@link AirspaceType }{@code >}
     *     {@link JAXBElement }{@code <}{@link AltimeterSourceType }{@code >}
     *     {@link JAXBElement }{@code <}{@link AngleIndicationType }{@code >}
     *     {@link JAXBElement }{@code <}{@link ApproachLightingSystemType }{@code >}
     *     {@link JAXBElement }{@code <}{@link ApronElementType }{@code >}
     *     {@link JAXBElement }{@code <}{@link ApronLightSystemType }{@code >}
     *     {@link JAXBElement }{@code <}{@link ApronMarkingType }{@code >}
     *     {@link JAXBElement }{@code <}{@link ApronType }{@code >}
     *     {@link JAXBElement }{@code <}{@link ArrestingGearType }{@code >}
     *     {@link JAXBElement }{@code <}{@link ArrivalFeederLegType }{@code >}
     *     {@link JAXBElement }{@code <}{@link ArrivalLegType }{@code >}
     *     {@link JAXBElement }{@code <}{@link AuthorityForAirspaceType }{@code >}
     *     {@link JAXBElement }{@code <}{@link AzimuthType }{@code >}
     *     {@link JAXBElement }{@code <}{@link ChangeOverPointType }{@code >}
     *     {@link JAXBElement }{@code <}{@link CheckpointINSType }{@code >}
     *     {@link JAXBElement }{@code <}{@link CheckpointVORType }{@code >}
     *     {@link JAXBElement }{@code <}{@link CirclingAreaType }{@code >}
     *     {@link JAXBElement }{@code <}{@link DMEType }{@code >}
     *     {@link JAXBElement }{@code <}{@link DeicingAreaMarkingType }{@code >}
     *     {@link JAXBElement }{@code <}{@link DeicingAreaType }{@code >}
     *     {@link JAXBElement }{@code <}{@link DepartureLegType }{@code >}
     *     {@link JAXBElement }{@code <}{@link DesignatedPointType }{@code >}
     *     {@link JAXBElement }{@code <}{@link DirectionFinderType }{@code >}
     *     {@link JAXBElement }{@code <}{@link DistanceIndicationType }{@code >}
     *     {@link JAXBElement }{@code <}{@link ElevationType }{@code >}
     *     {@link JAXBElement }{@code <}{@link FinalLegType }{@code >}
     *     {@link JAXBElement }{@code <}{@link FireFightingServiceType }{@code >}
     *     {@link JAXBElement }{@code <}{@link FlightRestrictionType }{@code >}
     *     {@link JAXBElement }{@code <}{@link FloatingDockSiteType }{@code >}
     *     {@link JAXBElement }{@code <}{@link GeoBorderType }{@code >}
     *     {@link JAXBElement }{@code <}{@link GlidepathType }{@code >}
     *     {@link JAXBElement }{@code <}{@link GroundTrafficControlServiceType }{@code >}
     *     {@link JAXBElement }{@code <}{@link GuidanceLineLightSystemType }{@code >}
     *     {@link JAXBElement }{@code <}{@link GuidanceLineMarkingType }{@code >}
     *     {@link JAXBElement }{@code <}{@link GuidanceLineType }{@code >}
     *     {@link JAXBElement }{@code <}{@link HoldingAssessmentType }{@code >}
     *     {@link JAXBElement }{@code <}{@link HoldingPatternType }{@code >}
     *     {@link JAXBElement }{@code <}{@link InformationServiceType }{@code >}
     *     {@link JAXBElement }{@code <}{@link InitialLegType }{@code >}
     *     {@link JAXBElement }{@code <}{@link InstrumentApproachProcedureType }{@code >}
     *     {@link JAXBElement }{@code <}{@link IntermediateLegType }{@code >}
     *     {@link JAXBElement }{@code <}{@link LocalizerType }{@code >}
     *     {@link JAXBElement }{@code <}{@link MarkerBeaconType }{@code >}
     *     {@link JAXBElement }{@code <}{@link MarkingBuoyType }{@code >}
     *     {@link JAXBElement }{@code <}{@link MissedApproachLegType }{@code >}
     *     {@link JAXBElement }{@code <}{@link NDBType }{@code >}
     *     {@link JAXBElement }{@code <}{@link NavaidType }{@code >}
     *     {@link JAXBElement }{@code <}{@link NavigationAreaRestrictionType }{@code >}
     *     {@link JAXBElement }{@code <}{@link NavigationAreaType }{@code >}
     *     {@link JAXBElement }{@code <}{@link NonMovementAreaType }{@code >}
     *     {@link JAXBElement }{@code <}{@link ObstacleAreaType }{@code >}
     *     {@link JAXBElement }{@code <}{@link OrganisationAuthorityType }{@code >}
     *     {@link JAXBElement }{@code <}{@link PassengerLoadingBridgeType }{@code >}
     *     {@link JAXBElement }{@code <}{@link PassengerServiceType }{@code >}
     *     {@link JAXBElement }{@code <}{@link PilotControlledLightingType }{@code >}
     *     {@link JAXBElement }{@code <}{@link PrecisionApproachRadarType }{@code >}
     *     {@link JAXBElement }{@code <}{@link PrimarySurveillanceRadarType }{@code >}
     *     {@link JAXBElement }{@code <}{@link ProcedureDMEType }{@code >}
     *     {@link JAXBElement }{@code <}{@link RadarSystemType }{@code >}
     *     {@link JAXBElement }{@code <}{@link RadioCommunicationChannelType }{@code >}
     *     {@link JAXBElement }{@code <}{@link RadioFrequencyAreaType }{@code >}
     *     {@link JAXBElement }{@code <}{@link RoadType }{@code >}
     *     {@link JAXBElement }{@code <}{@link RouteDMEType }{@code >}
     *     {@link JAXBElement }{@code <}{@link RouteSegmentType }{@code >}
     *     {@link JAXBElement }{@code <}{@link RouteType }{@code >}
     *     {@link JAXBElement }{@code <}{@link RulesProceduresType }{@code >}
     *     {@link JAXBElement }{@code <}{@link RunwayBlastPadType }{@code >}
     *     {@link JAXBElement }{@code <}{@link RunwayCentrelinePointType }{@code >}
     *     {@link JAXBElement }{@code <}{@link RunwayDirectionLightSystemType }{@code >}
     *     {@link JAXBElement }{@code <}{@link RunwayDirectionType }{@code >}
     *     {@link JAXBElement }{@code <}{@link RunwayElementType }{@code >}
     *     {@link JAXBElement }{@code <}{@link RunwayMarkingType }{@code >}
     *     {@link JAXBElement }{@code <}{@link RunwayProtectAreaLightSystemType }{@code >}
     *     {@link JAXBElement }{@code <}{@link RunwayProtectAreaType }{@code >}
     *     {@link JAXBElement }{@code <}{@link RunwayType }{@code >}
     *     {@link JAXBElement }{@code <}{@link RunwayVisualRangeType }{@code >}
     *     {@link JAXBElement }{@code <}{@link SDFType }{@code >}
     *     {@link JAXBElement }{@code <}{@link SafeAltitudeAreaType }{@code >}
     *     {@link JAXBElement }{@code <}{@link SeaplaneLandingAreaType }{@code >}
     *     {@link JAXBElement }{@code <}{@link SeaplaneRampSiteType }{@code >}
     *     {@link JAXBElement }{@code <}{@link SearchRescueServiceType }{@code >}
     *     {@link JAXBElement }{@code <}{@link SecondarySurveillanceRadarType }{@code >}
     *     {@link JAXBElement }{@code <}{@link SignificantPointInAirspaceType }{@code >}
     *     {@link JAXBElement }{@code <}{@link SpecialDateType }{@code >}
     *     {@link JAXBElement }{@code <}{@link SpecialNavigationStationType }{@code >}
     *     {@link JAXBElement }{@code <}{@link SpecialNavigationSystemType }{@code >}
     *     {@link JAXBElement }{@code <}{@link StandMarkingType }{@code >}
     *     {@link JAXBElement }{@code <}{@link StandardInstrumentArrivalType }{@code >}
     *     {@link JAXBElement }{@code <}{@link StandardInstrumentDepartureType }{@code >}
     *     {@link JAXBElement }{@code <}{@link StandardLevelColumnType }{@code >}
     *     {@link JAXBElement }{@code <}{@link StandardLevelSectorType }{@code >}
     *     {@link JAXBElement }{@code <}{@link StandardLevelTableType }{@code >}
     *     {@link JAXBElement }{@code <}{@link SurveyControlPointType }{@code >}
     *     {@link JAXBElement }{@code <}{@link TACANType }{@code >}
     *     {@link JAXBElement }{@code <}{@link TaxiHoldingPositionLightSystemType }{@code >}
     *     {@link JAXBElement }{@code <}{@link TaxiHoldingPositionMarkingType }{@code >}
     *     {@link JAXBElement }{@code <}{@link TaxiHoldingPositionType }{@code >}
     *     {@link JAXBElement }{@code <}{@link TaxiwayElementType }{@code >}
     *     {@link JAXBElement }{@code <}{@link TaxiwayLightSystemType }{@code >}
     *     {@link JAXBElement }{@code <}{@link TaxiwayMarkingType }{@code >}
     *     {@link JAXBElement }{@code <}{@link TaxiwayType }{@code >}
     *     {@link JAXBElement }{@code <}{@link TerminalArrivalAreaType }{@code >}
     *     {@link JAXBElement }{@code <}{@link TouchDownLiftOffLightSystemType }{@code >}
     *     {@link JAXBElement }{@code <}{@link TouchDownLiftOffMarkingType }{@code >}
     *     {@link JAXBElement }{@code <}{@link TouchDownLiftOffSafeAreaType }{@code >}
     *     {@link JAXBElement }{@code <}{@link TouchDownLiftOffType }{@code >}
     *     {@link JAXBElement }{@code <}{@link UnitType }{@code >}
     *     {@link JAXBElement }{@code <}{@link UnplannedHoldingType }{@code >}
     *     {@link JAXBElement }{@code <}{@link VORType }{@code >}
     *     {@link JAXBElement }{@code <}{@link VerticalStructureType }{@code >}
     *     {@link JAXBElement }{@code <}{@link VisualGlideSlopeIndicatorType }{@code >}
     *     {@link JAXBElement }{@code <}{@link WorkAreaType }{@code >}
     *     {@link JAXBElement }{@code <}{@link AIXMBasicMessageType }{@code >}
     *     {@link JAXBElement }{@code <}{@link AbstractContinuousCoverageType }{@code >}
     *     {@link JAXBElement }{@code <}{@link AbstractCoverageType }{@code >}
     *     {@link JAXBElement }{@code <}{@link AbstractFeatureCollectionType }{@code >}
     *     {@link JAXBElement }{@code <}{@link AbstractFeatureType }{@code >}
     *     {@link JAXBElement }{@code <}{@link DirectedObservationAtDistanceType }{@code >}
     *     {@link JAXBElement }{@code <}{@link DirectedObservationType }{@code >}
     *     {@link JAXBElement }{@code <}{@link DiscreteCoverageType }{@code >}
     *     {@link JAXBElement }{@code <}{@link DiscreteCoverageType }{@code >}
     *     {@link JAXBElement }{@code <}{@link DiscreteCoverageType }{@code >}
     *     {@link JAXBElement }{@code <}{@link DiscreteCoverageType }{@code >}
     *     {@link JAXBElement }{@code <}{@link DiscreteCoverageType }{@code >}
     *     {@link JAXBElement }{@code <}{@link DiscreteCoverageType }{@code >}
     *     {@link JAXBElement }{@code <}{@link DiscreteCoverageType }{@code >}
     *     {@link JAXBElement }{@code <}{@link DynamicFeatureCollectionType }{@code >}
     *     {@link JAXBElement }{@code <}{@link DynamicFeatureType }{@code >}
     *     {@link JAXBElement }{@code <}{@link FeatureCollectionType }{@code >}
     *     {@link JAXBElement }{@code <}{@link ObservationType }{@code >}
     *     
     */
    public JAXBElement<? extends AbstractFeatureType> getAbstractFeature() {
        return abstractFeature;
    }

    /**
     * Sets the value of the abstractFeature property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link AbstractAIXMFeatureType }{@code >}
     *     {@link JAXBElement }{@code <}{@link AbstractAirportGroundServiceType }{@code >}
     *     {@link JAXBElement }{@code <}{@link AbstractAirportHeliportProtectionAreaType }{@code >}
     *     {@link JAXBElement }{@code <}{@link AbstractApproachLegType }{@code >}
     *     {@link JAXBElement }{@code <}{@link AbstractGroundLightSystemType }{@code >}
     *     {@link JAXBElement }{@code <}{@link AbstractMarkingType }{@code >}
     *     {@link JAXBElement }{@code <}{@link AbstractNavaidEquipmentType }{@code >}
     *     {@link JAXBElement }{@code <}{@link AbstractNavigationSystemCheckpointType }{@code >}
     *     {@link JAXBElement }{@code <}{@link AbstractProcedureType }{@code >}
     *     {@link JAXBElement }{@code <}{@link AbstractRadarEquipmentType }{@code >}
     *     {@link JAXBElement }{@code <}{@link AbstractSegmentLegType }{@code >}
     *     {@link JAXBElement }{@code <}{@link AbstractServiceType }{@code >}
     *     {@link JAXBElement }{@code <}{@link AbstractSurveillanceRadarType }{@code >}
     *     {@link JAXBElement }{@code <}{@link AbstractTrafficSeparationServiceType }{@code >}
     *     {@link JAXBElement }{@code <}{@link AerialRefuellingType }{@code >}
     *     {@link JAXBElement }{@code <}{@link AeronauticalGroundLightType }{@code >}
     *     {@link JAXBElement }{@code <}{@link AirTrafficControlServiceType }{@code >}
     *     {@link JAXBElement }{@code <}{@link AirTrafficManagementServiceType }{@code >}
     *     {@link JAXBElement }{@code <}{@link AircraftGroundServiceType }{@code >}
     *     {@link JAXBElement }{@code <}{@link AircraftStandType }{@code >}
     *     {@link JAXBElement }{@code <}{@link AirportClearanceServiceType }{@code >}
     *     {@link JAXBElement }{@code <}{@link AirportHeliportCollocationType }{@code >}
     *     {@link JAXBElement }{@code <}{@link AirportHeliportType }{@code >}
     *     {@link JAXBElement }{@code <}{@link AirportHotSpotType }{@code >}
     *     {@link JAXBElement }{@code <}{@link AirportProtectionAreaMarkingType }{@code >}
     *     {@link JAXBElement }{@code <}{@link AirportSuppliesServiceType }{@code >}
     *     {@link JAXBElement }{@code <}{@link AirspaceBorderCrossingType }{@code >}
     *     {@link JAXBElement }{@code <}{@link AirspaceType }{@code >}
     *     {@link JAXBElement }{@code <}{@link AltimeterSourceType }{@code >}
     *     {@link JAXBElement }{@code <}{@link AngleIndicationType }{@code >}
     *     {@link JAXBElement }{@code <}{@link ApproachLightingSystemType }{@code >}
     *     {@link JAXBElement }{@code <}{@link ApronElementType }{@code >}
     *     {@link JAXBElement }{@code <}{@link ApronLightSystemType }{@code >}
     *     {@link JAXBElement }{@code <}{@link ApronMarkingType }{@code >}
     *     {@link JAXBElement }{@code <}{@link ApronType }{@code >}
     *     {@link JAXBElement }{@code <}{@link ArrestingGearType }{@code >}
     *     {@link JAXBElement }{@code <}{@link ArrivalFeederLegType }{@code >}
     *     {@link JAXBElement }{@code <}{@link ArrivalLegType }{@code >}
     *     {@link JAXBElement }{@code <}{@link AuthorityForAirspaceType }{@code >}
     *     {@link JAXBElement }{@code <}{@link AzimuthType }{@code >}
     *     {@link JAXBElement }{@code <}{@link ChangeOverPointType }{@code >}
     *     {@link JAXBElement }{@code <}{@link CheckpointINSType }{@code >}
     *     {@link JAXBElement }{@code <}{@link CheckpointVORType }{@code >}
     *     {@link JAXBElement }{@code <}{@link CirclingAreaType }{@code >}
     *     {@link JAXBElement }{@code <}{@link DMEType }{@code >}
     *     {@link JAXBElement }{@code <}{@link DeicingAreaMarkingType }{@code >}
     *     {@link JAXBElement }{@code <}{@link DeicingAreaType }{@code >}
     *     {@link JAXBElement }{@code <}{@link DepartureLegType }{@code >}
     *     {@link JAXBElement }{@code <}{@link DesignatedPointType }{@code >}
     *     {@link JAXBElement }{@code <}{@link DirectionFinderType }{@code >}
     *     {@link JAXBElement }{@code <}{@link DistanceIndicationType }{@code >}
     *     {@link JAXBElement }{@code <}{@link ElevationType }{@code >}
     *     {@link JAXBElement }{@code <}{@link FinalLegType }{@code >}
     *     {@link JAXBElement }{@code <}{@link FireFightingServiceType }{@code >}
     *     {@link JAXBElement }{@code <}{@link FlightRestrictionType }{@code >}
     *     {@link JAXBElement }{@code <}{@link FloatingDockSiteType }{@code >}
     *     {@link JAXBElement }{@code <}{@link GeoBorderType }{@code >}
     *     {@link JAXBElement }{@code <}{@link GlidepathType }{@code >}
     *     {@link JAXBElement }{@code <}{@link GroundTrafficControlServiceType }{@code >}
     *     {@link JAXBElement }{@code <}{@link GuidanceLineLightSystemType }{@code >}
     *     {@link JAXBElement }{@code <}{@link GuidanceLineMarkingType }{@code >}
     *     {@link JAXBElement }{@code <}{@link GuidanceLineType }{@code >}
     *     {@link JAXBElement }{@code <}{@link HoldingAssessmentType }{@code >}
     *     {@link JAXBElement }{@code <}{@link HoldingPatternType }{@code >}
     *     {@link JAXBElement }{@code <}{@link InformationServiceType }{@code >}
     *     {@link JAXBElement }{@code <}{@link InitialLegType }{@code >}
     *     {@link JAXBElement }{@code <}{@link InstrumentApproachProcedureType }{@code >}
     *     {@link JAXBElement }{@code <}{@link IntermediateLegType }{@code >}
     *     {@link JAXBElement }{@code <}{@link LocalizerType }{@code >}
     *     {@link JAXBElement }{@code <}{@link MarkerBeaconType }{@code >}
     *     {@link JAXBElement }{@code <}{@link MarkingBuoyType }{@code >}
     *     {@link JAXBElement }{@code <}{@link MissedApproachLegType }{@code >}
     *     {@link JAXBElement }{@code <}{@link NDBType }{@code >}
     *     {@link JAXBElement }{@code <}{@link NavaidType }{@code >}
     *     {@link JAXBElement }{@code <}{@link NavigationAreaRestrictionType }{@code >}
     *     {@link JAXBElement }{@code <}{@link NavigationAreaType }{@code >}
     *     {@link JAXBElement }{@code <}{@link NonMovementAreaType }{@code >}
     *     {@link JAXBElement }{@code <}{@link ObstacleAreaType }{@code >}
     *     {@link JAXBElement }{@code <}{@link OrganisationAuthorityType }{@code >}
     *     {@link JAXBElement }{@code <}{@link PassengerLoadingBridgeType }{@code >}
     *     {@link JAXBElement }{@code <}{@link PassengerServiceType }{@code >}
     *     {@link JAXBElement }{@code <}{@link PilotControlledLightingType }{@code >}
     *     {@link JAXBElement }{@code <}{@link PrecisionApproachRadarType }{@code >}
     *     {@link JAXBElement }{@code <}{@link PrimarySurveillanceRadarType }{@code >}
     *     {@link JAXBElement }{@code <}{@link ProcedureDMEType }{@code >}
     *     {@link JAXBElement }{@code <}{@link RadarSystemType }{@code >}
     *     {@link JAXBElement }{@code <}{@link RadioCommunicationChannelType }{@code >}
     *     {@link JAXBElement }{@code <}{@link RadioFrequencyAreaType }{@code >}
     *     {@link JAXBElement }{@code <}{@link RoadType }{@code >}
     *     {@link JAXBElement }{@code <}{@link RouteDMEType }{@code >}
     *     {@link JAXBElement }{@code <}{@link RouteSegmentType }{@code >}
     *     {@link JAXBElement }{@code <}{@link RouteType }{@code >}
     *     {@link JAXBElement }{@code <}{@link RulesProceduresType }{@code >}
     *     {@link JAXBElement }{@code <}{@link RunwayBlastPadType }{@code >}
     *     {@link JAXBElement }{@code <}{@link RunwayCentrelinePointType }{@code >}
     *     {@link JAXBElement }{@code <}{@link RunwayDirectionLightSystemType }{@code >}
     *     {@link JAXBElement }{@code <}{@link RunwayDirectionType }{@code >}
     *     {@link JAXBElement }{@code <}{@link RunwayElementType }{@code >}
     *     {@link JAXBElement }{@code <}{@link RunwayMarkingType }{@code >}
     *     {@link JAXBElement }{@code <}{@link RunwayProtectAreaLightSystemType }{@code >}
     *     {@link JAXBElement }{@code <}{@link RunwayProtectAreaType }{@code >}
     *     {@link JAXBElement }{@code <}{@link RunwayType }{@code >}
     *     {@link JAXBElement }{@code <}{@link RunwayVisualRangeType }{@code >}
     *     {@link JAXBElement }{@code <}{@link SDFType }{@code >}
     *     {@link JAXBElement }{@code <}{@link SafeAltitudeAreaType }{@code >}
     *     {@link JAXBElement }{@code <}{@link SeaplaneLandingAreaType }{@code >}
     *     {@link JAXBElement }{@code <}{@link SeaplaneRampSiteType }{@code >}
     *     {@link JAXBElement }{@code <}{@link SearchRescueServiceType }{@code >}
     *     {@link JAXBElement }{@code <}{@link SecondarySurveillanceRadarType }{@code >}
     *     {@link JAXBElement }{@code <}{@link SignificantPointInAirspaceType }{@code >}
     *     {@link JAXBElement }{@code <}{@link SpecialDateType }{@code >}
     *     {@link JAXBElement }{@code <}{@link SpecialNavigationStationType }{@code >}
     *     {@link JAXBElement }{@code <}{@link SpecialNavigationSystemType }{@code >}
     *     {@link JAXBElement }{@code <}{@link StandMarkingType }{@code >}
     *     {@link JAXBElement }{@code <}{@link StandardInstrumentArrivalType }{@code >}
     *     {@link JAXBElement }{@code <}{@link StandardInstrumentDepartureType }{@code >}
     *     {@link JAXBElement }{@code <}{@link StandardLevelColumnType }{@code >}
     *     {@link JAXBElement }{@code <}{@link StandardLevelSectorType }{@code >}
     *     {@link JAXBElement }{@code <}{@link StandardLevelTableType }{@code >}
     *     {@link JAXBElement }{@code <}{@link SurveyControlPointType }{@code >}
     *     {@link JAXBElement }{@code <}{@link TACANType }{@code >}
     *     {@link JAXBElement }{@code <}{@link TaxiHoldingPositionLightSystemType }{@code >}
     *     {@link JAXBElement }{@code <}{@link TaxiHoldingPositionMarkingType }{@code >}
     *     {@link JAXBElement }{@code <}{@link TaxiHoldingPositionType }{@code >}
     *     {@link JAXBElement }{@code <}{@link TaxiwayElementType }{@code >}
     *     {@link JAXBElement }{@code <}{@link TaxiwayLightSystemType }{@code >}
     *     {@link JAXBElement }{@code <}{@link TaxiwayMarkingType }{@code >}
     *     {@link JAXBElement }{@code <}{@link TaxiwayType }{@code >}
     *     {@link JAXBElement }{@code <}{@link TerminalArrivalAreaType }{@code >}
     *     {@link JAXBElement }{@code <}{@link TouchDownLiftOffLightSystemType }{@code >}
     *     {@link JAXBElement }{@code <}{@link TouchDownLiftOffMarkingType }{@code >}
     *     {@link JAXBElement }{@code <}{@link TouchDownLiftOffSafeAreaType }{@code >}
     *     {@link JAXBElement }{@code <}{@link TouchDownLiftOffType }{@code >}
     *     {@link JAXBElement }{@code <}{@link UnitType }{@code >}
     *     {@link JAXBElement }{@code <}{@link UnplannedHoldingType }{@code >}
     *     {@link JAXBElement }{@code <}{@link VORType }{@code >}
     *     {@link JAXBElement }{@code <}{@link VerticalStructureType }{@code >}
     *     {@link JAXBElement }{@code <}{@link VisualGlideSlopeIndicatorType }{@code >}
     *     {@link JAXBElement }{@code <}{@link WorkAreaType }{@code >}
     *     {@link JAXBElement }{@code <}{@link AIXMBasicMessageType }{@code >}
     *     {@link JAXBElement }{@code <}{@link AbstractContinuousCoverageType }{@code >}
     *     {@link JAXBElement }{@code <}{@link AbstractCoverageType }{@code >}
     *     {@link JAXBElement }{@code <}{@link AbstractFeatureCollectionType }{@code >}
     *     {@link JAXBElement }{@code <}{@link AbstractFeatureType }{@code >}
     *     {@link JAXBElement }{@code <}{@link DirectedObservationAtDistanceType }{@code >}
     *     {@link JAXBElement }{@code <}{@link DirectedObservationType }{@code >}
     *     {@link JAXBElement }{@code <}{@link DiscreteCoverageType }{@code >}
     *     {@link JAXBElement }{@code <}{@link DiscreteCoverageType }{@code >}
     *     {@link JAXBElement }{@code <}{@link DiscreteCoverageType }{@code >}
     *     {@link JAXBElement }{@code <}{@link DiscreteCoverageType }{@code >}
     *     {@link JAXBElement }{@code <}{@link DiscreteCoverageType }{@code >}
     *     {@link JAXBElement }{@code <}{@link DiscreteCoverageType }{@code >}
     *     {@link JAXBElement }{@code <}{@link DiscreteCoverageType }{@code >}
     *     {@link JAXBElement }{@code <}{@link DynamicFeatureCollectionType }{@code >}
     *     {@link JAXBElement }{@code <}{@link DynamicFeatureType }{@code >}
     *     {@link JAXBElement }{@code <}{@link FeatureCollectionType }{@code >}
     *     {@link JAXBElement }{@code <}{@link ObservationType }{@code >}
     *     
     * @see #getAbstractFeature()
     */
    public void setAbstractFeature(JAXBElement<? extends AbstractFeatureType> value) {
        this.abstractFeature = value;
    }

    public boolean isSetAbstractFeature() {
        return (this.abstractFeature!= null);
    }

    /**
     * Gets the value of the owns property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.Boolean }
     *     
     */
    public boolean isOwns() {
        if (owns == null) {
            return false;
        } else {
            return owns;
        }
    }

    /**
     * Sets the value of the owns property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.Boolean }
     *     
     */
    public void setOwns(boolean value) {
        this.owns = value;
    }

    public boolean isSetOwns() {
        return (this.owns!= null);
    }

    public void unsetOwns() {
        this.owns = null;
    }

    /**
     * Gets the value of the nilReason property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the nilReason property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getNilReason().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * </p>
     * 
     * 
     * @return
     *     The value of the nilReason property.
     */
    public List<String> getNilReason() {
        if (nilReason == null) {
            nilReason = new ArrayList<>();
        }
        return this.nilReason;
    }

    public boolean isSetNilReason() {
        return ((this.nilReason!= null)&&(!this.nilReason.isEmpty()));
    }

    public void unsetNilReason() {
        this.nilReason = null;
    }

    /**
     * Gets the value of the remoteSchema property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRemoteSchema() {
        return remoteSchema;
    }

    /**
     * Sets the value of the remoteSchema property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRemoteSchema(String value) {
        this.remoteSchema = value;
    }

    public boolean isSetRemoteSchema() {
        return (this.remoteSchema!= null);
    }

    /**
     * Gets the value of the href property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHref() {
        return href;
    }

    /**
     * Sets the value of the href property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHref(String value) {
        this.href = value;
    }

    public boolean isSetHref() {
        return (this.href!= null);
    }

    /**
     * Gets the value of the role property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRole() {
        return role;
    }

    /**
     * Sets the value of the role property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRole(String value) {
        this.role = value;
    }

    public boolean isSetRole() {
        return (this.role!= null);
    }

    /**
     * Gets the value of the arcrole property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArcrole() {
        return arcrole;
    }

    /**
     * Sets the value of the arcrole property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArcrole(String value) {
        this.arcrole = value;
    }

    public boolean isSetArcrole() {
        return (this.arcrole!= null);
    }

    /**
     * Gets the value of the titleAttribute property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitleAttribute() {
        return titleAttribute;
    }

    /**
     * Sets the value of the titleAttribute property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitleAttribute(String value) {
        this.titleAttribute = value;
    }

    public boolean isSetTitleAttribute() {
        return (this.titleAttribute!= null);
    }

    /**
     * Gets the value of the show property.
     * 
     * @return
     *     possible object is
     *     {@link ShowType }
     *     
     */
    public ShowType getShow() {
        return show;
    }

    /**
     * Sets the value of the show property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShowType }
     *     
     */
    public void setShow(ShowType value) {
        this.show = value;
    }

    public boolean isSetShow() {
        return (this.show!= null);
    }

    /**
     * Gets the value of the actuate property.
     * 
     * @return
     *     possible object is
     *     {@link ActuateType }
     *     
     */
    public ActuateType getActuate() {
        return actuate;
    }

    /**
     * Sets the value of the actuate property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActuateType }
     *     
     */
    public void setActuate(ActuateType value) {
        this.actuate = value;
    }

    public boolean isSetActuate() {
        return (this.actuate!= null);
    }

}
