//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.aixm.delorean.core.org.gml;

import java.util.ArrayList;
import java.util.List;
import com.aixm.delorean.core.aixm.AerialRefuellingTimeSliceType;
import com.aixm.delorean.core.aixm.AeronauticalGroundLightTimeSliceType;
import com.aixm.delorean.core.aixm.AirTrafficControlServiceTimeSliceType;
import com.aixm.delorean.core.aixm.AirTrafficManagementServiceTimeSliceType;
import com.aixm.delorean.core.aixm.AircraftGroundServiceTimeSliceType;
import com.aixm.delorean.core.aixm.AircraftStandTimeSliceType;
import com.aixm.delorean.core.aixm.AirportClearanceServiceTimeSliceType;
import com.aixm.delorean.core.aixm.AirportHeliportCollocationTimeSliceType;
import com.aixm.delorean.core.aixm.AirportHeliportTimeSliceType;
import com.aixm.delorean.core.aixm.AirportHotSpotTimeSliceType;
import com.aixm.delorean.core.aixm.AirportProtectionAreaMarkingTimeSliceType;
import com.aixm.delorean.core.aixm.AirportSuppliesServiceTimeSliceType;
import com.aixm.delorean.core.aixm.AirspaceBorderCrossingTimeSliceType;
import com.aixm.delorean.core.aixm.AirspaceTimeSliceType;
import com.aixm.delorean.core.aixm.AltimeterSourceTimeSliceType;
import com.aixm.delorean.core.aixm.AngleIndicationTimeSliceType;
import com.aixm.delorean.core.aixm.ApproachLightingSystemTimeSliceType;
import com.aixm.delorean.core.aixm.ApronElementTimeSliceType;
import com.aixm.delorean.core.aixm.ApronLightSystemTimeSliceType;
import com.aixm.delorean.core.aixm.ApronMarkingTimeSliceType;
import com.aixm.delorean.core.aixm.ApronTimeSliceType;
import com.aixm.delorean.core.aixm.ArrestingGearTimeSliceType;
import com.aixm.delorean.core.aixm.ArrivalFeederLegTimeSliceType;
import com.aixm.delorean.core.aixm.ArrivalLegTimeSliceType;
import com.aixm.delorean.core.aixm.AuthorityForAirspaceTimeSliceType;
import com.aixm.delorean.core.aixm.AzimuthTimeSliceType;
import com.aixm.delorean.core.aixm.ChangeOverPointTimeSliceType;
import com.aixm.delorean.core.aixm.CheckpointINSTimeSliceType;
import com.aixm.delorean.core.aixm.CheckpointVORTimeSliceType;
import com.aixm.delorean.core.aixm.CirclingAreaTimeSliceType;
import com.aixm.delorean.core.aixm.DMETimeSliceType;
import com.aixm.delorean.core.aixm.DeicingAreaMarkingTimeSliceType;
import com.aixm.delorean.core.aixm.DeicingAreaTimeSliceType;
import com.aixm.delorean.core.aixm.DepartureLegTimeSliceType;
import com.aixm.delorean.core.aixm.DesignatedPointTimeSliceType;
import com.aixm.delorean.core.aixm.DirectionFinderTimeSliceType;
import com.aixm.delorean.core.aixm.DistanceIndicationTimeSliceType;
import com.aixm.delorean.core.aixm.ElevationTimeSliceType;
import com.aixm.delorean.core.aixm.FinalLegTimeSliceType;
import com.aixm.delorean.core.aixm.FireFightingServiceTimeSliceType;
import com.aixm.delorean.core.aixm.FlightRestrictionTimeSliceType;
import com.aixm.delorean.core.aixm.FloatingDockSiteTimeSliceType;
import com.aixm.delorean.core.aixm.GeoBorderTimeSliceType;
import com.aixm.delorean.core.aixm.GlidepathTimeSliceType;
import com.aixm.delorean.core.aixm.GroundTrafficControlServiceTimeSliceType;
import com.aixm.delorean.core.aixm.GuidanceLineLightSystemTimeSliceType;
import com.aixm.delorean.core.aixm.GuidanceLineMarkingTimeSliceType;
import com.aixm.delorean.core.aixm.GuidanceLineTimeSliceType;
import com.aixm.delorean.core.aixm.HoldingAssessmentTimeSliceType;
import com.aixm.delorean.core.aixm.HoldingPatternTimeSliceType;
import com.aixm.delorean.core.aixm.InformationServiceTimeSliceType;
import com.aixm.delorean.core.aixm.InitialLegTimeSliceType;
import com.aixm.delorean.core.aixm.InstrumentApproachProcedureTimeSliceType;
import com.aixm.delorean.core.aixm.IntermediateLegTimeSliceType;
import com.aixm.delorean.core.aixm.LocalizerTimeSliceType;
import com.aixm.delorean.core.aixm.MarkerBeaconTimeSliceType;
import com.aixm.delorean.core.aixm.MarkingBuoyTimeSliceType;
import com.aixm.delorean.core.aixm.MissedApproachLegTimeSliceType;
import com.aixm.delorean.core.aixm.NDBTimeSliceType;
import com.aixm.delorean.core.aixm.NavaidTimeSliceType;
import com.aixm.delorean.core.aixm.NavigationAreaRestrictionTimeSliceType;
import com.aixm.delorean.core.aixm.NavigationAreaTimeSliceType;
import com.aixm.delorean.core.aixm.NonMovementAreaTimeSliceType;
import com.aixm.delorean.core.aixm.ObstacleAreaTimeSliceType;
import com.aixm.delorean.core.aixm.OrganisationAuthorityTimeSliceType;
import com.aixm.delorean.core.aixm.PassengerLoadingBridgeTimeSliceType;
import com.aixm.delorean.core.aixm.PassengerServiceTimeSliceType;
import com.aixm.delorean.core.aixm.PilotControlledLightingTimeSliceType;
import com.aixm.delorean.core.aixm.PrecisionApproachRadarTimeSliceType;
import com.aixm.delorean.core.aixm.PrimarySurveillanceRadarTimeSliceType;
import com.aixm.delorean.core.aixm.ProcedureDMETimeSliceType;
import com.aixm.delorean.core.aixm.RadarSystemTimeSliceType;
import com.aixm.delorean.core.aixm.RadioCommunicationChannelTimeSliceType;
import com.aixm.delorean.core.aixm.RadioFrequencyAreaTimeSliceType;
import com.aixm.delorean.core.aixm.RoadTimeSliceType;
import com.aixm.delorean.core.aixm.RouteDMETimeSliceType;
import com.aixm.delorean.core.aixm.RouteSegmentTimeSliceType;
import com.aixm.delorean.core.aixm.RouteTimeSliceType;
import com.aixm.delorean.core.aixm.RulesProceduresTimeSliceType;
import com.aixm.delorean.core.aixm.RunwayBlastPadTimeSliceType;
import com.aixm.delorean.core.aixm.RunwayCentrelinePointTimeSliceType;
import com.aixm.delorean.core.aixm.RunwayDirectionLightSystemTimeSliceType;
import com.aixm.delorean.core.aixm.RunwayDirectionTimeSliceType;
import com.aixm.delorean.core.aixm.RunwayElementTimeSliceType;
import com.aixm.delorean.core.aixm.RunwayMarkingTimeSliceType;
import com.aixm.delorean.core.aixm.RunwayProtectAreaLightSystemTimeSliceType;
import com.aixm.delorean.core.aixm.RunwayProtectAreaTimeSliceType;
import com.aixm.delorean.core.aixm.RunwayTimeSliceType;
import com.aixm.delorean.core.aixm.RunwayVisualRangeTimeSliceType;
import com.aixm.delorean.core.aixm.SDFTimeSliceType;
import com.aixm.delorean.core.aixm.SafeAltitudeAreaTimeSliceType;
import com.aixm.delorean.core.aixm.SeaplaneLandingAreaTimeSliceType;
import com.aixm.delorean.core.aixm.SeaplaneRampSiteTimeSliceType;
import com.aixm.delorean.core.aixm.SearchRescueServiceTimeSliceType;
import com.aixm.delorean.core.aixm.SecondarySurveillanceRadarTimeSliceType;
import com.aixm.delorean.core.aixm.SignificantPointInAirspaceTimeSliceType;
import com.aixm.delorean.core.aixm.SpecialDateTimeSliceType;
import com.aixm.delorean.core.aixm.SpecialNavigationStationTimeSliceType;
import com.aixm.delorean.core.aixm.SpecialNavigationSystemTimeSliceType;
import com.aixm.delorean.core.aixm.StandMarkingTimeSliceType;
import com.aixm.delorean.core.aixm.StandardInstrumentArrivalTimeSliceType;
import com.aixm.delorean.core.aixm.StandardInstrumentDepartureTimeSliceType;
import com.aixm.delorean.core.aixm.StandardLevelColumnTimeSliceType;
import com.aixm.delorean.core.aixm.StandardLevelSectorTimeSliceType;
import com.aixm.delorean.core.aixm.StandardLevelTableTimeSliceType;
import com.aixm.delorean.core.aixm.SurveyControlPointTimeSliceType;
import com.aixm.delorean.core.aixm.TACANTimeSliceType;
import com.aixm.delorean.core.aixm.TaxiHoldingPositionLightSystemTimeSliceType;
import com.aixm.delorean.core.aixm.TaxiHoldingPositionMarkingTimeSliceType;
import com.aixm.delorean.core.aixm.TaxiHoldingPositionTimeSliceType;
import com.aixm.delorean.core.aixm.TaxiwayElementTimeSliceType;
import com.aixm.delorean.core.aixm.TaxiwayLightSystemTimeSliceType;
import com.aixm.delorean.core.aixm.TaxiwayMarkingTimeSliceType;
import com.aixm.delorean.core.aixm.TaxiwayTimeSliceType;
import com.aixm.delorean.core.aixm.TerminalArrivalAreaTimeSliceType;
import com.aixm.delorean.core.aixm.TouchDownLiftOffLightSystemTimeSliceType;
import com.aixm.delorean.core.aixm.TouchDownLiftOffMarkingTimeSliceType;
import com.aixm.delorean.core.aixm.TouchDownLiftOffSafeAreaTimeSliceType;
import com.aixm.delorean.core.aixm.TouchDownLiftOffTimeSliceType;
import com.aixm.delorean.core.aixm.UnitTimeSliceType;
import com.aixm.delorean.core.aixm.UnplannedHoldingTimeSliceType;
import com.aixm.delorean.core.aixm.VORTimeSliceType;
import com.aixm.delorean.core.aixm.VerticalStructureTimeSliceType;
import com.aixm.delorean.core.aixm.VisualGlideSlopeIndicatorTimeSliceType;
import com.aixm.delorean.core.aixm.WorkAreaTimeSliceType;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for HistoryPropertyType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="HistoryPropertyType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element ref="{http://www.opengis.net/gml/3.2}AbstractTimeSlice" maxOccurs="unbounded"/>
 *       </sequence>
 *       <attGroup ref="{http://www.opengis.net/gml/3.2}OwnershipAttributeGroup"/>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HistoryPropertyType", propOrder = {
    "abstractTimeSlice"
})
public class HistoryPropertyType {

    /**
     * To describe an event — an action that occurs at an instant or over an interval of time — GML provides the gml:AbtractTimeSlice element. A timeslice encapsulates the time-varying properties of a dynamic feature -- it shall be extended to represent a time stamped projection of a specific feature. The gml:dataSource property describes how the temporal data was acquired.
     * A gml:AbstractTimeSlice instance is a GML object that encapsulates updates of the dynamic—or volatile—properties that reflect some change event; it thus includes only those feature properties that have actually changed due to some process.
     * gml:AbstractTimeSlice basically provides a facility for attribute-level time stamping, in contrast to the object-level time stamping of dynamic feature instances. 
     * The time slice can thus be viewed as event or process-oriented, whereas a snapshot is more state or structure-oriented. A timeslice has richer causality, whereas a snapshot merely portrays the status of the whole.
     * 
     */
    @XmlElementRef(name = "AbstractTimeSlice", namespace = "http://www.opengis.net/gml/3.2", type = JAXBElement.class)
    protected List<JAXBElement<? extends AbstractTimeSliceType>> abstractTimeSlice;
    @XmlAttribute(name = "owns")
    protected java.lang.Boolean owns;

    /**
     * To describe an event — an action that occurs at an instant or over an interval of time — GML provides the gml:AbtractTimeSlice element. A timeslice encapsulates the time-varying properties of a dynamic feature -- it shall be extended to represent a time stamped projection of a specific feature. The gml:dataSource property describes how the temporal data was acquired.
     * A gml:AbstractTimeSlice instance is a GML object that encapsulates updates of the dynamic—or volatile—properties that reflect some change event; it thus includes only those feature properties that have actually changed due to some process.
     * gml:AbstractTimeSlice basically provides a facility for attribute-level time stamping, in contrast to the object-level time stamping of dynamic feature instances. 
     * The time slice can thus be viewed as event or process-oriented, whereas a snapshot is more state or structure-oriented. A timeslice has richer causality, whereas a snapshot merely portrays the status of the whole.
     * 
     * Gets the value of the abstractTimeSlice property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the abstractTimeSlice property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getAbstractTimeSlice().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link AerialRefuellingTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link AeronauticalGroundLightTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link AirTrafficControlServiceTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link AirTrafficManagementServiceTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link AircraftGroundServiceTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link AircraftStandTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link AirportClearanceServiceTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link AirportHeliportCollocationTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link AirportHeliportTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link AirportHotSpotTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link AirportProtectionAreaMarkingTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link AirportSuppliesServiceTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link AirspaceBorderCrossingTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link AirspaceTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link AltimeterSourceTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link AngleIndicationTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link ApproachLightingSystemTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link ApronElementTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link ApronLightSystemTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link ApronMarkingTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link ApronTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link ArrestingGearTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link ArrivalFeederLegTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link ArrivalLegTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link AuthorityForAirspaceTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link AzimuthTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link ChangeOverPointTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link CheckpointINSTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link CheckpointVORTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link CirclingAreaTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link DMETimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link DeicingAreaMarkingTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link DeicingAreaTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link DepartureLegTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link DesignatedPointTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link DirectionFinderTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link DistanceIndicationTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link ElevationTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link FinalLegTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link FireFightingServiceTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link FlightRestrictionTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link FloatingDockSiteTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link GeoBorderTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link GlidepathTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link GroundTrafficControlServiceTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link GuidanceLineLightSystemTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link GuidanceLineMarkingTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link GuidanceLineTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link HoldingAssessmentTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link HoldingPatternTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link InformationServiceTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link InitialLegTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link InstrumentApproachProcedureTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link IntermediateLegTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link LocalizerTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link MarkerBeaconTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link MarkingBuoyTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link MissedApproachLegTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link NDBTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link NavaidTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link NavigationAreaRestrictionTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link NavigationAreaTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link NonMovementAreaTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link ObstacleAreaTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link OrganisationAuthorityTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link PassengerLoadingBridgeTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link PassengerServiceTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link PilotControlledLightingTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link PrecisionApproachRadarTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link PrimarySurveillanceRadarTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link ProcedureDMETimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link RadarSystemTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link RadioCommunicationChannelTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link RadioFrequencyAreaTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link RoadTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link RouteDMETimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link RouteSegmentTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link RouteTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link RulesProceduresTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link RunwayBlastPadTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link RunwayCentrelinePointTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link RunwayDirectionLightSystemTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link RunwayDirectionTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link RunwayElementTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link RunwayMarkingTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link RunwayProtectAreaLightSystemTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link RunwayProtectAreaTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link RunwayTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link RunwayVisualRangeTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link SDFTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link SafeAltitudeAreaTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link SeaplaneLandingAreaTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link SeaplaneRampSiteTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link SearchRescueServiceTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link SecondarySurveillanceRadarTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link SignificantPointInAirspaceTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link SpecialDateTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link SpecialNavigationStationTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link SpecialNavigationSystemTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link StandMarkingTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link StandardInstrumentArrivalTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link StandardInstrumentDepartureTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link StandardLevelColumnTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link StandardLevelSectorTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link StandardLevelTableTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link SurveyControlPointTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link TACANTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link TaxiHoldingPositionLightSystemTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link TaxiHoldingPositionMarkingTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link TaxiHoldingPositionTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link TaxiwayElementTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link TaxiwayLightSystemTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link TaxiwayMarkingTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link TaxiwayTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link TerminalArrivalAreaTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link TouchDownLiftOffLightSystemTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link TouchDownLiftOffMarkingTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link TouchDownLiftOffSafeAreaTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link TouchDownLiftOffTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link UnitTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link UnplannedHoldingTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link VORTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link VerticalStructureTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link VisualGlideSlopeIndicatorTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link WorkAreaTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link AbstractTimeSliceType }{@code >}
     * {@link JAXBElement }{@code <}{@link MovingObjectStatusType }{@code >}
     * </p>
     * 
     * 
     * @return
     *     The value of the abstractTimeSlice property.
     */
    public List<JAXBElement<? extends AbstractTimeSliceType>> getAbstractTimeSlice() {
        if (abstractTimeSlice == null) {
            abstractTimeSlice = new ArrayList<>();
        }
        return this.abstractTimeSlice;
    }

    public boolean isSetAbstractTimeSlice() {
        return ((this.abstractTimeSlice!= null)&&(!this.abstractTimeSlice.isEmpty()));
    }

    public void unsetAbstractTimeSlice() {
        this.abstractTimeSlice = null;
    }

    /**
     * Gets the value of the owns property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.Boolean }
     *     
     */
    public boolean isOwns() {
        if (owns == null) {
            return false;
        } else {
            return owns;
        }
    }

    /**
     * Sets the value of the owns property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.Boolean }
     *     
     */
    public void setOwns(boolean value) {
        this.owns = value;
    }

    public boolean isSetOwns() {
        return (this.owns!= null);
    }

    public void unsetOwns() {
        this.owns = null;
    }

}
