//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.aixm.delorean.core.schema.a5_1_1.aixm;

import jakarta.persistence.Entity;
import jakarta.persistence.Inheritance;
import jakarta.persistence.InheritanceType;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Adds the FeatureMetadata, which is common to all AIXM features
 * 
 * <p>Java class for AbstractAIXMObjectType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="AbstractAIXMObjectType">
 *   <complexContent>
 *     <extension base="{http://www.aixm.aero/schema/5.1.1}AbstractAIXMObjectBaseType">
 *       <sequence>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AbstractAIXMObjectType", propOrder = {

})
@XmlSeeAlso({
    AbstractExtensionType.class,
    AerialRefuellingAnchorType.class,
    AerialRefuellingTrackType.class,
    AuthorityForAerialRefuellingType.class,
    CityType.class,
    SurfaceCharacteristicsType.class,
    LightActivationType.class,
    MarkingElementType.class,
    AbstractUsageConditionType.class,
    NavaidEquipmentDistanceType.class,
    RunwayDeclaredDistanceType.class,
    RidgeType.class,
    SurfaceContaminationLayerType.class,
    AbstractSurfaceContaminationType.class,
    AirspaceGeometryComponentType.class,
    AirspaceVolumeType.class,
    AirspaceVolumeDependencyType.class,
    HoldingPatternDistanceType.class,
    HoldingPatternDurationType.class,
    AuthorityForNavaidEquipmentType.class,
    AuthorityForSpecialNavigationStationType.class,
    AuthorityForSpecialNavigationSystemType.class,
    NavaidComponentType.class,
    AngleUseType.class,
    PointReferenceType.class,
    AbstractSegmentPointType.class,
    LinguisticNoteType.class,
    NoteType.class,
    OrganisationAuthorityAssociationType.class,
    UnitDependencyType.class,
    ApproachAltitudeTableType.class,
    ApproachConditionType.class,
    ApproachDistanceTableType.class,
    ApproachTimingTableType.class,
    FinalProfileType.class,
    MissedApproachGroupType.class,
    TerminalArrivalAreaSectorType.class,
    FASDataBlockType.class,
    EquipmentUnavailableAdjustmentType.class,
    EquipmentUnavailableAdjustmentColumnType.class,
    MinimaType.class,
    DepartureArrivalConditionType.class,
    NavigationAreaSectorType.class,
    SectorDesignType.class,
    SafeAltitudeAreaSectorType.class,
    HoldingUseType.class,
    LandingTakeoffAreaCollectionType.class,
    ProcedureTransitionType.class,
    ProcedureTransitionLegType.class,
    RoutePortionType.class,
    AbstractDirectFlightType.class,
    FlightConditionCircumstanceType.class,
    FlightConditionElementType.class,
    FlightRestrictionLevelType.class,
    FlightRestrictionRouteType.class,
    FlightRoutingElementType.class,
    CallsignDetailType.class,
    FuelType.class,
    NitrogenType.class,
    OilType.class,
    OxygenType.class,
    ContactInformationType.class,
    AircraftCharacteristicType.class,
    FlightCharacteristicType.class,
    AirspaceLayerType.class,
    CircleSectorType.class,
    LightElementType.class,
    AbstractPropertiesWithScheduleType.class,
    MeteorologyType.class,
    TimesheetType.class,
    StandardLevelType.class,
    AltitudeAdjustmentType.class,
    ObstacleAssessmentAreaType.class,
    ObstaclePlacementType.class,
    ObstructionType.class,
    RadarComponentType.class,
    ReflectorType.class,
    SurveillanceGroundStationType.class
})
@Entity
@Inheritance(strategy = InheritanceType.TABLE_PER_CLASS)
public abstract class AbstractAIXMObjectType
    extends AbstractAIXMObjectBaseType
{


}
