//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.aixm.delorean.core.schema.a5_1_1.aixm;

import com.aixm.delorean.core.adapter.type.gis.AixmElevatedSurfaceType;
import jakarta.xml.bind.annotation.adapters.XmlAdapter;

public class Adapter3
    extends XmlAdapter<String, AixmElevatedSurfaceType>
{


    public AixmElevatedSurfaceType unmarshal(String value) {
        return new AixmElevatedSurfaceType(value);
    }

    public String marshal(AixmElevatedSurfaceType value) {
        if (value == null) {
            return null;
        }
        return value.toString();
    }

}
