//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.aixm.delorean.core.schema.a5_1_1.aixm;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CodeGuidanceLineBaseType</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * <pre>{@code
 * <simpleType name="CodeGuidanceLineBaseType">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="RWY"/>
 *     <enumeration value="TWY"/>
 *     <enumeration value="APRON"/>
 *     <enumeration value="GATE_TLANE"/>
 *     <enumeration value="LI_TLANE"/>
 *     <enumeration value="LO_TLANE"/>
 *     <enumeration value="AIR_TLANE"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "CodeGuidanceLineBaseType")
@XmlEnum
public enum CodeGuidanceLineBaseType {

    RWY,
    TWY,
    APRON,
    GATE_TLANE,
    LI_TLANE,
    LO_TLANE,
    AIR_TLANE;

    public String value() {
        return name();
    }

    public static CodeGuidanceLineBaseType fromValue(String v) {
        return valueOf(v);
    }

}
