//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.aixm.delorean.core.schema.a5_1_1.aixm;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 * 
 * <p>Java class for CodeRadioFrequencyAreaBaseType</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * <pre>{@code
 * <simpleType name="CodeRadioFrequencyAreaBaseType">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="COV"/>
 *     <enumeration value="T_COV"/>
 *     <enumeration value="SCL"/>
 *     <enumeration value="RHG"/>
 *     <enumeration value="UNREL"/>
 *     <enumeration value="RES"/>
 *     <enumeration value="UUS"/>
 *     <enumeration value="OUT"/>
 *     <enumeration value="ESV"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "CodeRadioFrequencyAreaBaseType")
@XmlEnum
public enum CodeRadioFrequencyAreaBaseType {

    COV,
    T_COV,
    SCL,
    RHG,
    UNREL,
    RES,
    UUS,
    OUT,
    ESV;

    public String value() {
        return name();
    }

    public static CodeRadioFrequencyAreaBaseType fromValue(String v) {
        return valueOf(v);
    }

}
