//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.aixm.delorean.core.schema.a5_1_1.aixm;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CodeAirportWarningBaseType</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * <pre>{@code
 * <simpleType name="CodeAirportWarningBaseType">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="WIP"/>
 *     <enumeration value="EQUIP"/>
 *     <enumeration value="BIRD"/>
 *     <enumeration value="ANIMAL"/>
 *     <enumeration value="RUBBER_REMOVAL"/>
 *     <enumeration value="PARKED_ACFT"/>
 *     <enumeration value="RESURFACING"/>
 *     <enumeration value="PAVING"/>
 *     <enumeration value="PAINTING"/>
 *     <enumeration value="INSPECTION"/>
 *     <enumeration value="GRASS_CUTTING"/>
 *     <enumeration value="CALIBRATION"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "CodeAirportWarningBaseType")
@XmlEnum
public enum CodeAirportWarningBaseType {

    WIP,
    EQUIP,
    BIRD,
    ANIMAL,
    RUBBER_REMOVAL,
    PARKED_ACFT,
    RESURFACING,
    PAVING,
    PAINTING,
    INSPECTION,
    GRASS_CUTTING,
    CALIBRATION;

    public String value() {
        return name();
    }

    public static CodeAirportWarningBaseType fromValue(String v) {
        return valueOf(v);
    }

}
