//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.aixm.delorean.core.schema.a5_1_1.aixm;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 * 
 * <p>Java class for CodeRunwayPointRoleBaseType</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * <pre>{@code
 * <simpleType name="CodeRunwayPointRoleBaseType">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="START"/>
 *     <enumeration value="THR"/>
 *     <enumeration value="DISTHR"/>
 *     <enumeration value="TDZ"/>
 *     <enumeration value="MID"/>
 *     <enumeration value="END"/>
 *     <enumeration value="START_RUN"/>
 *     <enumeration value="LAHSO"/>
 *     <enumeration value="ABEAM_GLIDESLOPE"/>
 *     <enumeration value="ABEAM_PAR"/>
 *     <enumeration value="ABEAM_ELEVATION"/>
 *     <enumeration value="ABEAM_TDR"/>
 *     <enumeration value="ABEAM_RER"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "CodeRunwayPointRoleBaseType")
@XmlEnum
public enum CodeRunwayPointRoleBaseType {

    START,
    THR,
    DISTHR,
    TDZ,
    MID,
    END,
    START_RUN,
    LAHSO,
    ABEAM_GLIDESLOPE,
    ABEAM_PAR,
    ABEAM_ELEVATION,
    ABEAM_TDR,
    ABEAM_RER;

    public String value() {
        return name();
    }

    public static CodeRunwayPointRoleBaseType fromValue(String v) {
        return valueOf(v);
    }

}
