//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.aixm.delorean.core.schema.a5_1_1.aixm;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 * 
 * <p>Java class for CodeMarkerBeaconSignalBaseType</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * <pre>{@code
 * <simpleType name="CodeMarkerBeaconSignalBaseType">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="FAN"/>
 *     <enumeration value="LOW_PWR_FAN"/>
 *     <enumeration value="Z"/>
 *     <enumeration value="BONES"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "CodeMarkerBeaconSignalBaseType")
@XmlEnum
public enum CodeMarkerBeaconSignalBaseType {

    FAN,
    LOW_PWR_FAN,
    Z,
    BONES;

    public String value() {
        return name();
    }

    public static CodeMarkerBeaconSignalBaseType fromValue(String v) {
        return valueOf(v);
    }

}
