//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.aixm.delorean.core.schema.a5_1_1.aixm;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CodeRunwayMarkingBaseType</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * <pre>{@code
 * <simpleType name="CodeRunwayMarkingBaseType">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="PRECISION"/>
 *     <enumeration value="NONPRECISION"/>
 *     <enumeration value="BASIC"/>
 *     <enumeration value="NONE"/>
 *     <enumeration value="RUNWAY_NUMBERS"/>
 *     <enumeration value="NON_STANDARD"/>
 *     <enumeration value="HELIPORT"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "CodeRunwayMarkingBaseType")
@XmlEnum
public enum CodeRunwayMarkingBaseType {

    PRECISION,
    NONPRECISION,
    BASIC,
    NONE,
    RUNWAY_NUMBERS,
    NON_STANDARD,
    HELIPORT;

    public String value() {
        return name();
    }

    public static CodeRunwayMarkingBaseType fromValue(String v) {
        return valueOf(v);
    }

}
