//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.aixm.delorean.core.schema.a5_1_1.aixm;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CodeRadioEmissionBaseType</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * <pre>{@code
 * <simpleType name="CodeRadioEmissionBaseType">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="A2"/>
 *     <enumeration value="A3A"/>
 *     <enumeration value="A3B"/>
 *     <enumeration value="A3E"/>
 *     <enumeration value="A3H"/>
 *     <enumeration value="A3J"/>
 *     <enumeration value="A3L"/>
 *     <enumeration value="A3U"/>
 *     <enumeration value="J3E"/>
 *     <enumeration value="NONA1A"/>
 *     <enumeration value="NONA2A"/>
 *     <enumeration value="PON"/>
 *     <enumeration value="A8W"/>
 *     <enumeration value="A9W"/>
 *     <enumeration value="NOX"/>
 *     <enumeration value="G1D"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "CodeRadioEmissionBaseType")
@XmlEnum
public enum CodeRadioEmissionBaseType {

    A2,
    A3A,
    A3B,
    A3E,
    A3H,
    A3J,
    A3L,
    A3U,
    J3E,
    NONA1A,
    NONA2A,
    PON,
    A8W,
    A9W,
    NOX,
    G1D;

    public String value() {
        return name();
    }

    public static CodeRadioEmissionBaseType fromValue(String v) {
        return valueOf(v);
    }

}
