//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.aixm.delorean.core.schema.a5_1_1.aixm;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for CodeAirspaceActivityBaseType simple type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <simpleType name="CodeAirspaceActivityBaseType">
 *   <union>
 *     <simpleType>
 *       <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *         <enumeration value="AD_TFC"/>
 *         <enumeration value="HELI_TFC"/>
 *         <enumeration value="TRAINING"/>
 *         <enumeration value="AEROBATICS"/>
 *         <enumeration value="AIRSHOW"/>
 *         <enumeration value="SPORT"/>
 *         <enumeration value="ULM"/>
 *         <enumeration value="GLIDING"/>
 *         <enumeration value="PARAGLIDER"/>
 *         <enumeration value="HANGGLIDING"/>
 *         <enumeration value="PARACHUTE"/>
 *         <enumeration value="AIR_DROP"/>
 *         <enumeration value="BALLOON"/>
 *         <enumeration value="RADIOSONDE"/>
 *         <enumeration value="SPACE_FLIGHT"/>
 *         <enumeration value="UAV"/>
 *         <enumeration value="AERIAL_WORK"/>
 *         <enumeration value="CROP_DUSTING"/>
 *         <enumeration value="FIRE_FIGHTING"/>
 *         <enumeration value="MILOPS"/>
 *         <enumeration value="REFUEL"/>
 *         <enumeration value="JET_CLIMBING"/>
 *         <enumeration value="EXERCISE"/>
 *         <enumeration value="TOWING"/>
 *         <enumeration value="NAVAL_EXER"/>
 *         <enumeration value="MISSILES"/>
 *         <enumeration value="AIR_GUN"/>
 *         <enumeration value="ARTILLERY"/>
 *         <enumeration value="SHOOTING"/>
 *         <enumeration value="BLASTING"/>
 *         <enumeration value="WATER_BLASTING"/>
 *         <enumeration value="ANTI_HAIL"/>
 *         <enumeration value="BIRD"/>
 *         <enumeration value="BIRD_MIGRATION"/>
 *         <enumeration value="FIREWORK"/>
 *         <enumeration value="HI_RADIO"/>
 *         <enumeration value="HI_LIGHT"/>
 *         <enumeration value="LASER"/>
 *         <enumeration value="NATURE"/>
 *         <enumeration value="FAUNA"/>
 *         <enumeration value="NO_NOISE"/>
 *         <enumeration value="ACCIDENT"/>
 *         <enumeration value="POPULATION"/>
 *         <enumeration value="VIP"/>
 *         <enumeration value="VIP_PRES"/>
 *         <enumeration value="VIP_VICE"/>
 *         <enumeration value="OIL"/>
 *         <enumeration value="GAS"/>
 *         <enumeration value="REFINERY"/>
 *         <enumeration value="CHEMICAL"/>
 *         <enumeration value="NUCLEAR"/>
 *         <enumeration value="TECHNICAL"/>
 *         <enumeration value="ATS"/>
 *         <enumeration value="PROCEDURE"/>
 *       </restriction>
 *     </simpleType>
 *     <simpleType>
 *       <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *         <pattern value="OTHER(:(\w|_){1,58})?"/>
 *       </restriction>
 *     </simpleType>
 *   </union>
 * </simpleType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CodeAirspaceActivityBaseType", propOrder = {
    "value"
})
public class CodeAirspaceActivityBaseType {

    @XmlValue
    protected String value;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    public boolean isSetValue() {
        return (this.value!= null);
    }

}
