//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.aixm.delorean.core.schema.a5_1_1.aixm;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CodePassengerServiceBaseType</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * <pre>{@code
 * <simpleType name="CodePassengerServiceBaseType">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     <enumeration value="CUST"/>
 *     <enumeration value="SAN"/>
 *     <enumeration value="SECUR"/>
 *     <enumeration value="VET"/>
 *     <enumeration value="HOTEL"/>
 *     <enumeration value="TRANSPORT"/>
 *     <enumeration value="REST"/>
 *     <enumeration value="INFO"/>
 *     <enumeration value="BANK"/>
 *     <enumeration value="POST"/>
 *     <enumeration value="MEDIC"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "CodePassengerServiceBaseType")
@XmlEnum
public enum CodePassengerServiceBaseType {

    CUST,
    SAN,
    SECUR,
    VET,
    HOTEL,
    TRANSPORT,
    REST,
    INFO,
    BANK,
    POST,
    MEDIC;

    public String value() {
        return name();
    }

    public static CodePassengerServiceBaseType fromValue(String v) {
        return valueOf(v);
    }

}
