//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.aixm.delorean.core.schema.a5_1_1.aixm;

import java.util.ArrayList;
import java.util.List;
import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ElevatedSurfaceType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="ElevatedSurfaceType">
 *   <complexContent>
 *     <extension base="{http://www.aixm.aero/schema/5.1.1}SurfaceType">
 *       <sequence>
 *         <group ref="{http://www.aixm.aero/schema/5.1.1}ElevatedSurfacePropertyGroup"/>
 *         <element name="extension" maxOccurs="unbounded" minOccurs="0">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <choice>
 *                   <element ref="{http://www.aixm.aero/schema/5.1.1}AbstractElevatedSurfaceExtension"/>
 *                 </choice>
 *                 <attGroup ref="{http://www.opengis.net/gml/3.2}OwnershipAttributeGroup"/>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ElevatedSurfaceType", propOrder = {
    "elevation",
    "geoidUndulation",
    "verticalDatum",
    "verticalAccuracy",
    "extension"
})
@Entity
@Table(name = "elevated_surface_type")
public class ElevatedSurfaceType
    extends SurfaceType
{

    @XmlElement(nillable = true)
    @Column(name = "elevation")
    protected ValDistanceVerticalType elevation;
    @XmlElement(nillable = true)
    @Column(name = "geoid_undulation")
    protected ValDistanceSignedType geoidUndulation;
    @XmlElement(nillable = true)
    @Column(name = "vertical_datum")
    protected CodeVerticalDatumType verticalDatum;
    @XmlElement(nillable = true)
    @Column(name = "vertical_accuracy")
    protected ValDistanceType verticalAccuracy;
    @OneToMany(cascade = {
        CascadeType.ALL
    }, orphanRemoval = true, fetch = FetchType.EAGER)
    protected List<ElevatedSurfaceType.Extension> extension;

    /**
     * Gets the value of the elevation property.
     * 
     * @return
     *     possible object is
     *     {@link ValDistanceVerticalType }
     *     
     */
    public ValDistanceVerticalType getElevation() {
        return elevation;
    }

    /**
     * Sets the value of the elevation property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValDistanceVerticalType }
     *     
     */
    public void setElevation(ValDistanceVerticalType value) {
        this.elevation = value;
    }

    public boolean isSetElevation() {
        return (this.elevation!= null);
    }

    /**
     * Gets the value of the geoidUndulation property.
     * 
     * @return
     *     possible object is
     *     {@link ValDistanceSignedType }
     *     
     */
    public ValDistanceSignedType getGeoidUndulation() {
        return geoidUndulation;
    }

    /**
     * Sets the value of the geoidUndulation property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValDistanceSignedType }
     *     
     */
    public void setGeoidUndulation(ValDistanceSignedType value) {
        this.geoidUndulation = value;
    }

    public boolean isSetGeoidUndulation() {
        return (this.geoidUndulation!= null);
    }

    /**
     * Gets the value of the verticalDatum property.
     * 
     * @return
     *     possible object is
     *     {@link CodeVerticalDatumType }
     *     
     */
    public CodeVerticalDatumType getVerticalDatum() {
        return verticalDatum;
    }

    /**
     * Sets the value of the verticalDatum property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeVerticalDatumType }
     *     
     */
    public void setVerticalDatum(CodeVerticalDatumType value) {
        this.verticalDatum = value;
    }

    public boolean isSetVerticalDatum() {
        return (this.verticalDatum!= null);
    }

    /**
     * Gets the value of the verticalAccuracy property.
     * 
     * @return
     *     possible object is
     *     {@link ValDistanceType }
     *     
     */
    public ValDistanceType getVerticalAccuracy() {
        return verticalAccuracy;
    }

    /**
     * Sets the value of the verticalAccuracy property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValDistanceType }
     *     
     */
    public void setVerticalAccuracy(ValDistanceType value) {
        this.verticalAccuracy = value;
    }

    public boolean isSetVerticalAccuracy() {
        return (this.verticalAccuracy!= null);
    }

    /**
     * Gets the value of the extension property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the extension property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getExtension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ElevatedSurfaceType.Extension }
     * </p>
     * 
     * 
     * @return
     *     The value of the extension property.
     */
    public List<ElevatedSurfaceType.Extension> getExtension() {
        if (extension == null) {
            extension = new ArrayList<>();
        }
        return this.extension;
    }

    public boolean isSetExtension() {
        return ((this.extension!= null)&&(!this.extension.isEmpty()));
    }

    public void unsetExtension() {
        this.extension = null;
    }


    /**
     * <p>Java class for anonymous complex type</p>.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.</p>
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <choice>
     *         <element ref="{http://www.aixm.aero/schema/5.1.1}AbstractElevatedSurfaceExtension"/>
     *       </choice>
     *       <attGroup ref="{http://www.opengis.net/gml/3.2}OwnershipAttributeGroup"/>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "abstractElevatedSurfaceExtension"
    })
    public static class Extension {

        @XmlElement(name = "AbstractElevatedSurfaceExtension")
        @Column(name = "aixm:_abstract_elevated_surface_extension")
        protected AbstractExtensionType abstractElevatedSurfaceExtension;
        @XmlAttribute(name = "owns")
        protected Boolean owns;

        /**
         * Gets the value of the abstractElevatedSurfaceExtension property.
         * 
         * @return
         *     possible object is
         *     {@link AbstractExtensionType }
         *     
         */
        public AbstractExtensionType getAbstractElevatedSurfaceExtension() {
            return abstractElevatedSurfaceExtension;
        }

        /**
         * Sets the value of the abstractElevatedSurfaceExtension property.
         * 
         * @param value
         *     allowed object is
         *     {@link AbstractExtensionType }
         *     
         */
        public void setAbstractElevatedSurfaceExtension(AbstractExtensionType value) {
            this.abstractElevatedSurfaceExtension = value;
        }

        public boolean isSetAbstractElevatedSurfaceExtension() {
            return (this.abstractElevatedSurfaceExtension!= null);
        }

        /**
         * Gets the value of the owns property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public boolean isOwns() {
            if (owns == null) {
                return false;
            } else {
                return owns;
            }
        }

        /**
         * Sets the value of the owns property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setOwns(boolean value) {
            this.owns = value;
        }

        public boolean isSetOwns() {
            return (this.owns!= null);
        }

        public void unsetOwns() {
            this.owns = null;
        }

    }

}
