//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.aixm.delorean.core.schema.a5_1_1.aixm;

import java.util.ArrayList;
import java.util.List;
import jakarta.persistence.AttributeOverride;
import jakarta.persistence.AttributeOverrides;
import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Embedded;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.JoinTable;
import jakarta.persistence.OneToMany;
import jakarta.persistence.OneToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Transient;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FASDataBlockType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="FASDataBlockType">
 *   <complexContent>
 *     <extension base="{http://www.aixm.aero/schema/5.1.1}AbstractAIXMObjectType">
 *       <sequence>
 *         <group ref="{http://www.aixm.aero/schema/5.1.1}FASDataBlockPropertyGroup"/>
 *         <element name="extension" maxOccurs="unbounded" minOccurs="0">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <choice>
 *                   <element ref="{http://www.aixm.aero/schema/5.1.1}AbstractFASDataBlockExtension"/>
 *                 </choice>
 *                 <attGroup ref="{http://www.opengis.net/gml/3.2}OwnershipAttributeGroup"/>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FASDataBlockType", propOrder = {
    "horizontalAlarmLimit",
    "verticalAlarmLimit",
    "thresholdCourseWidth",
    "lengthOffset",
    "crcRemainder",
    "operationType",
    "serviceProviderSBAS",
    "approachPerformanceDesignator",
    "routeIndicator",
    "referencePathDataSelector",
    "referencePathIdentifier",
    "codeICAO",
    "annotation",
    "extension"
})
@Entity
@Table(name = "fasdatablock", schema = "public")
public class FASDataBlockType
    extends AbstractAIXMObjectType
{

    @XmlElement(nillable = true)
    @Embedded
    @AttributeOverrides({
        @AttributeOverride(name = "value", column = @Column(name = "horizontalalarmlimit_value", length = 255, columnDefinition = "DECIMAL", nullable = true, unique = false)),
        @AttributeOverride(name = "nilReason", column = @Column(name = "horizontalalarmlimit_nilreason", length = 255, nullable = true, unique = false))
    })
    protected ValAlarmLimitType horizontalAlarmLimit;
    @XmlElement(nillable = true)
    @Embedded
    @AttributeOverrides({
        @AttributeOverride(name = "value", column = @Column(name = "verticalalarmlimit_value", length = 255, columnDefinition = "DECIMAL", nullable = true, unique = false)),
        @AttributeOverride(name = "nilReason", column = @Column(name = "verticalalarmlimit_nilreason", length = 255, nullable = true, unique = false))
    })
    protected ValAlarmLimitType verticalAlarmLimit;
    @XmlElement(nillable = true)
    @Embedded
    @AttributeOverrides({
        @AttributeOverride(name = "value", column = @Column(name = "thresholdcoursewidth_value", length = 255, columnDefinition = "DECIMAL", nullable = true, unique = false)),
        @AttributeOverride(name = "uom", column = @Column(name = "thresholdcoursewidth_uom", length = 255, nullable = true, unique = false)),
        @AttributeOverride(name = "nilReason", column = @Column(name = "thresholdcoursewidth_nilreason", length = 255, nullable = true, unique = false))
    })
    protected ValDistanceType thresholdCourseWidth;
    @XmlElement(nillable = true)
    @Embedded
    @AttributeOverrides({
        @AttributeOverride(name = "value", column = @Column(name = "lengthoffset_value", length = 255, columnDefinition = "DECIMAL", nullable = true, unique = false)),
        @AttributeOverride(name = "uom", column = @Column(name = "lengthoffset_uom", length = 255, nullable = true, unique = false)),
        @AttributeOverride(name = "nilReason", column = @Column(name = "lengthoffset_nilreason", length = 255, nullable = true, unique = false))
    })
    protected ValDistanceType lengthOffset;
    @XmlElement(name = "CRCRemainder", nillable = true)
    @Embedded
    @AttributeOverrides({
        @AttributeOverride(name = "value", column = @Column(name = "crcremainder_value", length = 255, columnDefinition = "TEXT", nullable = true, unique = false)),
        @AttributeOverride(name = "nilReason", column = @Column(name = "crcremainder_nilreason", length = 255, nullable = true, unique = false))
    })
    protected ValHexType crcRemainder;
    @XmlElement(nillable = true)
    @Embedded
    @AttributeOverrides({
        @AttributeOverride(name = "value", column = @Column(name = "operationtype_value", length = 255, nullable = true, unique = false)),
        @AttributeOverride(name = "nilReason", column = @Column(name = "operationtype_nilreason", length = 255, nullable = true, unique = false))
    })
    protected NoSequenceType operationType;
    @XmlElement(nillable = true)
    @Embedded
    @AttributeOverrides({
        @AttributeOverride(name = "value", column = @Column(name = "serviceprovidersbas_value", length = 255, nullable = true, unique = false)),
        @AttributeOverride(name = "nilReason", column = @Column(name = "serviceprovidersbas_nilreason", length = 255, nullable = true, unique = false))
    })
    protected NoSequenceType serviceProviderSBAS;
    @XmlElement(nillable = true)
    @Embedded
    @AttributeOverrides({
        @AttributeOverride(name = "value", column = @Column(name = "approachperformancedesignator_value", length = 255, nullable = true, unique = false)),
        @AttributeOverride(name = "nilReason", column = @Column(name = "approachperformancedesignator_nilreason", length = 255, nullable = true, unique = false))
    })
    protected NoSequenceType approachPerformanceDesignator;
    @XmlElement(nillable = true)
    @Embedded
    @AttributeOverrides({
        @AttributeOverride(name = "value", column = @Column(name = "routeindicator_value", length = 255, columnDefinition = "TEXT", nullable = true, unique = false)),
        @AttributeOverride(name = "nilReason", column = @Column(name = "routeindicator_nilreason", length = 255, nullable = true, unique = false))
    })
    protected CodeRouteIndicatorType routeIndicator;
    @XmlElement(nillable = true)
    @Embedded
    @AttributeOverrides({
        @AttributeOverride(name = "value", column = @Column(name = "referencepathdataselector_value", length = 255, nullable = true, unique = false)),
        @AttributeOverride(name = "nilReason", column = @Column(name = "referencepathdataselector_nilreason", length = 255, nullable = true, unique = false))
    })
    protected NoSequenceType referencePathDataSelector;
    @XmlElement(nillable = true)
    @Embedded
    @AttributeOverrides({
        @AttributeOverride(name = "value", column = @Column(name = "referencepathidentifier_value", length = 255, columnDefinition = "TEXT", nullable = true, unique = false)),
        @AttributeOverride(name = "nilReason", column = @Column(name = "referencepathidentifier_nilreason", length = 255, nullable = true, unique = false))
    })
    protected CodeReferencePathIdentifierType referencePathIdentifier;
    @XmlElement(nillable = true)
    @Embedded
    @AttributeOverrides({
        @AttributeOverride(name = "value", column = @Column(name = "codeicao_value", length = 255, columnDefinition = "TEXT", nullable = true, unique = false)),
        @AttributeOverride(name = "nilReason", column = @Column(name = "codeicao_nilreason", length = 255, nullable = true, unique = false))
    })
    protected CodeICAOCountryType codeICAO;
    @XmlElement(nillable = true)
    @OneToMany(cascade = {
        CascadeType.ALL
    }, fetch = FetchType.EAGER)
    @JoinTable(name = "master_join", joinColumns = {
        @JoinColumn(name = "source_id")
    }, inverseJoinColumns = {
        @JoinColumn(name = "target_id")
    })
    protected List<NotePropertyType> annotation;
    @Transient
    protected List<FASDataBlockType.Extension> extension;

    /**
     * Gets the value of the horizontalAlarmLimit property.
     * 
     * @return
     *     possible object is
     *     {@link ValAlarmLimitType }
     *     
     */
    public ValAlarmLimitType getHorizontalAlarmLimit() {
        return horizontalAlarmLimit;
    }

    /**
     * Sets the value of the horizontalAlarmLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValAlarmLimitType }
     *     
     */
    public void setHorizontalAlarmLimit(ValAlarmLimitType value) {
        this.horizontalAlarmLimit = value;
    }

    public boolean isSetHorizontalAlarmLimit() {
        return (this.horizontalAlarmLimit!= null);
    }

    /**
     * Gets the value of the verticalAlarmLimit property.
     * 
     * @return
     *     possible object is
     *     {@link ValAlarmLimitType }
     *     
     */
    public ValAlarmLimitType getVerticalAlarmLimit() {
        return verticalAlarmLimit;
    }

    /**
     * Sets the value of the verticalAlarmLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValAlarmLimitType }
     *     
     */
    public void setVerticalAlarmLimit(ValAlarmLimitType value) {
        this.verticalAlarmLimit = value;
    }

    public boolean isSetVerticalAlarmLimit() {
        return (this.verticalAlarmLimit!= null);
    }

    /**
     * Gets the value of the thresholdCourseWidth property.
     * 
     * @return
     *     possible object is
     *     {@link ValDistanceType }
     *     
     */
    public ValDistanceType getThresholdCourseWidth() {
        return thresholdCourseWidth;
    }

    /**
     * Sets the value of the thresholdCourseWidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValDistanceType }
     *     
     */
    public void setThresholdCourseWidth(ValDistanceType value) {
        this.thresholdCourseWidth = value;
    }

    public boolean isSetThresholdCourseWidth() {
        return (this.thresholdCourseWidth!= null);
    }

    /**
     * Gets the value of the lengthOffset property.
     * 
     * @return
     *     possible object is
     *     {@link ValDistanceType }
     *     
     */
    public ValDistanceType getLengthOffset() {
        return lengthOffset;
    }

    /**
     * Sets the value of the lengthOffset property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValDistanceType }
     *     
     */
    public void setLengthOffset(ValDistanceType value) {
        this.lengthOffset = value;
    }

    public boolean isSetLengthOffset() {
        return (this.lengthOffset!= null);
    }

    /**
     * Gets the value of the crcRemainder property.
     * 
     * @return
     *     possible object is
     *     {@link ValHexType }
     *     
     */
    public ValHexType getCRCRemainder() {
        return crcRemainder;
    }

    /**
     * Sets the value of the crcRemainder property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValHexType }
     *     
     */
    public void setCRCRemainder(ValHexType value) {
        this.crcRemainder = value;
    }

    public boolean isSetCRCRemainder() {
        return (this.crcRemainder!= null);
    }

    /**
     * Gets the value of the operationType property.
     * 
     * @return
     *     possible object is
     *     {@link NoSequenceType }
     *     
     */
    public NoSequenceType getOperationType() {
        return operationType;
    }

    /**
     * Sets the value of the operationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link NoSequenceType }
     *     
     */
    public void setOperationType(NoSequenceType value) {
        this.operationType = value;
    }

    public boolean isSetOperationType() {
        return (this.operationType!= null);
    }

    /**
     * Gets the value of the serviceProviderSBAS property.
     * 
     * @return
     *     possible object is
     *     {@link NoSequenceType }
     *     
     */
    public NoSequenceType getServiceProviderSBAS() {
        return serviceProviderSBAS;
    }

    /**
     * Sets the value of the serviceProviderSBAS property.
     * 
     * @param value
     *     allowed object is
     *     {@link NoSequenceType }
     *     
     */
    public void setServiceProviderSBAS(NoSequenceType value) {
        this.serviceProviderSBAS = value;
    }

    public boolean isSetServiceProviderSBAS() {
        return (this.serviceProviderSBAS!= null);
    }

    /**
     * Gets the value of the approachPerformanceDesignator property.
     * 
     * @return
     *     possible object is
     *     {@link NoSequenceType }
     *     
     */
    public NoSequenceType getApproachPerformanceDesignator() {
        return approachPerformanceDesignator;
    }

    /**
     * Sets the value of the approachPerformanceDesignator property.
     * 
     * @param value
     *     allowed object is
     *     {@link NoSequenceType }
     *     
     */
    public void setApproachPerformanceDesignator(NoSequenceType value) {
        this.approachPerformanceDesignator = value;
    }

    public boolean isSetApproachPerformanceDesignator() {
        return (this.approachPerformanceDesignator!= null);
    }

    /**
     * Gets the value of the routeIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link CodeRouteIndicatorType }
     *     
     */
    public CodeRouteIndicatorType getRouteIndicator() {
        return routeIndicator;
    }

    /**
     * Sets the value of the routeIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeRouteIndicatorType }
     *     
     */
    public void setRouteIndicator(CodeRouteIndicatorType value) {
        this.routeIndicator = value;
    }

    public boolean isSetRouteIndicator() {
        return (this.routeIndicator!= null);
    }

    /**
     * Gets the value of the referencePathDataSelector property.
     * 
     * @return
     *     possible object is
     *     {@link NoSequenceType }
     *     
     */
    public NoSequenceType getReferencePathDataSelector() {
        return referencePathDataSelector;
    }

    /**
     * Sets the value of the referencePathDataSelector property.
     * 
     * @param value
     *     allowed object is
     *     {@link NoSequenceType }
     *     
     */
    public void setReferencePathDataSelector(NoSequenceType value) {
        this.referencePathDataSelector = value;
    }

    public boolean isSetReferencePathDataSelector() {
        return (this.referencePathDataSelector!= null);
    }

    /**
     * Gets the value of the referencePathIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link CodeReferencePathIdentifierType }
     *     
     */
    public CodeReferencePathIdentifierType getReferencePathIdentifier() {
        return referencePathIdentifier;
    }

    /**
     * Sets the value of the referencePathIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeReferencePathIdentifierType }
     *     
     */
    public void setReferencePathIdentifier(CodeReferencePathIdentifierType value) {
        this.referencePathIdentifier = value;
    }

    public boolean isSetReferencePathIdentifier() {
        return (this.referencePathIdentifier!= null);
    }

    /**
     * Gets the value of the codeICAO property.
     * 
     * @return
     *     possible object is
     *     {@link CodeICAOCountryType }
     *     
     */
    public CodeICAOCountryType getCodeICAO() {
        return codeICAO;
    }

    /**
     * Sets the value of the codeICAO property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeICAOCountryType }
     *     
     */
    public void setCodeICAO(CodeICAOCountryType value) {
        this.codeICAO = value;
    }

    public boolean isSetCodeICAO() {
        return (this.codeICAO!= null);
    }

    /**
     * Gets the value of the annotation property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the annotation property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getAnnotation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NotePropertyType }
     * </p>
     * 
     * 
     * @return
     *     The value of the annotation property.
     */
    public List<NotePropertyType> getAnnotation() {
        if (annotation == null) {
            annotation = new ArrayList<>();
        }
        return this.annotation;
    }

    public boolean isSetAnnotation() {
        return ((this.annotation!= null)&&(!this.annotation.isEmpty()));
    }

    public void unsetAnnotation() {
        this.annotation = null;
    }

    /**
     * Gets the value of the extension property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the extension property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getExtension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FASDataBlockType.Extension }
     * </p>
     * 
     * 
     * @return
     *     The value of the extension property.
     */
    public List<FASDataBlockType.Extension> getExtension() {
        if (extension == null) {
            extension = new ArrayList<>();
        }
        return this.extension;
    }

    public boolean isSetExtension() {
        return ((this.extension!= null)&&(!this.extension.isEmpty()));
    }

    public void unsetExtension() {
        this.extension = null;
    }


    /**
     * <p>Java class for anonymous complex type</p>.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.</p>
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <choice>
     *         <element ref="{http://www.aixm.aero/schema/5.1.1}AbstractFASDataBlockExtension"/>
     *       </choice>
     *       <attGroup ref="{http://www.opengis.net/gml/3.2}OwnershipAttributeGroup"/>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "abstractFASDataBlockExtension"
    })
    public static class Extension {

        @XmlElement(name = "AbstractFASDataBlockExtension")
        @OneToOne(cascade = {
            CascadeType.ALL
        }, fetch = FetchType.EAGER)
        @JoinColumn(name = "abstractfasdatablockextension_id", referencedColumnName = "id")
        protected AbstractExtensionType abstractFASDataBlockExtension;
        @XmlAttribute(name = "owns")
        @Transient
        protected Boolean owns;

        /**
         * Gets the value of the abstractFASDataBlockExtension property.
         * 
         * @return
         *     possible object is
         *     {@link AbstractExtensionType }
         *     
         */
        public AbstractExtensionType getAbstractFASDataBlockExtension() {
            return abstractFASDataBlockExtension;
        }

        /**
         * Sets the value of the abstractFASDataBlockExtension property.
         * 
         * @param value
         *     allowed object is
         *     {@link AbstractExtensionType }
         *     
         */
        public void setAbstractFASDataBlockExtension(AbstractExtensionType value) {
            this.abstractFASDataBlockExtension = value;
        }

        public boolean isSetAbstractFASDataBlockExtension() {
            return (this.abstractFASDataBlockExtension!= null);
        }

        /**
         * Gets the value of the owns property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public boolean isOwns() {
            if (owns == null) {
                return false;
            } else {
                return owns;
            }
        }

        /**
         * Sets the value of the owns property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setOwns(boolean value) {
            this.owns = value;
        }

        public boolean isSetOwns() {
            return (this.owns!= null);
        }

        public void unsetOwns() {
            this.owns = null;
        }

    }

}
