//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.aixm.delorean.core.schema.a5_1_1.aixm;

import java.util.ArrayList;
import java.util.List;
import jakarta.persistence.AttributeOverride;
import jakarta.persistence.AttributeOverrides;
import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Embedded;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.JoinTable;
import jakarta.persistence.OneToMany;
import jakarta.persistence.OneToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Transient;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RunwayContaminationType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="RunwayContaminationType">
 *   <complexContent>
 *     <extension base="{http://www.aixm.aero/schema/5.1.1}AbstractSurfaceContaminationType">
 *       <sequence>
 *         <element name="observationTime" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         <element name="nextObservationTime" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         <group ref="{http://www.aixm.aero/schema/5.1.1}SurfaceContaminationPropertyGroup"/>
 *         <group ref="{http://www.aixm.aero/schema/5.1.1}RunwayContaminationPropertyGroup"/>
 *         <element name="extension" maxOccurs="unbounded" minOccurs="0">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 <choice>
 *                   <element ref="{http://www.aixm.aero/schema/5.1.1}AbstractSurfaceContaminationExtension"/>
 *                   <element ref="{http://www.aixm.aero/schema/5.1.1}AbstractRunwayContaminationExtension"/>
 *                 </choice>
 *                 <attGroup ref="{http://www.opengis.net/gml/3.2}OwnershipAttributeGroup"/>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RunwayContaminationType", propOrder = {
    "observationTime",
    "nextObservationTime",
    "depth",
    "frictionCoefficient",
    "frictionEstimation",
    "frictionDevice",
    "obscuredLights",
    "furtherClearanceTime",
    "furtherTotalClearance",
    "proportion",
    "criticalRidge",
    "layer",
    "annotation",
    "clearedLength",
    "clearedWidth",
    "clearedSide",
    "furtherClearanceLength",
    "furtherClearanceWidth",
    "obscuredLightsSide",
    "clearedLengthBegin",
    "taxiwayAvailable",
    "apronAvailable",
    "extension"
})
@Entity
@Table(name = "runwaycontamination", schema = "airport_heliport")
public class RunwayContaminationType
    extends AbstractSurfaceContaminationType
{

    /**
     * aixm:DateTimeType
     * 
     */
    @XmlElement(nillable = true)
    @Embedded
    @AttributeOverrides({
        @AttributeOverride(name = "value", column = @Column(name = "observationtime_value", length = 255, columnDefinition = "TIMESTAMP", nullable = true, unique = false)),
        @AttributeOverride(name = "nilReason", column = @Column(name = "observationtime_nilreason", length = 255, nullable = true, unique = false))
    })
    protected String observationTime;
    /**
     * aixm:DateTimeType
     * 
     */
    @XmlElement(nillable = true)
    @Embedded
    @AttributeOverrides({
        @AttributeOverride(name = "value", column = @Column(name = "nextobservationtime_value", length = 255, columnDefinition = "TIMESTAMP", nullable = true, unique = false)),
        @AttributeOverride(name = "nilReason", column = @Column(name = "nextobservationtime_nilreason", length = 255, nullable = true, unique = false))
    })
    protected String nextObservationTime;
    @XmlElement(nillable = true)
    @Embedded
    @AttributeOverrides({
        @AttributeOverride(name = "value", column = @Column(name = "depth_value", length = 255, columnDefinition = "DECIMAL", nullable = true, unique = false)),
        @AttributeOverride(name = "uom", column = @Column(name = "depth_uom", length = 255, nullable = true, unique = false)),
        @AttributeOverride(name = "nilReason", column = @Column(name = "depth_nilreason", length = 255, nullable = true, unique = false))
    })
    protected ValDepthType depth;
    @XmlElement(nillable = true)
    @Embedded
    @AttributeOverrides({
        @AttributeOverride(name = "value", column = @Column(name = "frictioncoefficient_value", length = 255, columnDefinition = "DECIMAL", nullable = true, unique = false)),
        @AttributeOverride(name = "nilReason", column = @Column(name = "frictioncoefficient_nilreason", length = 255, nullable = true, unique = false))
    })
    protected ValFrictionType frictionCoefficient;
    @XmlElement(nillable = true)
    @Embedded
    @AttributeOverrides({
        @AttributeOverride(name = "value", column = @Column(name = "frictionestimation_value", length = 255, nullable = true, unique = false)),
        @AttributeOverride(name = "nilReason", column = @Column(name = "frictionestimation_nilreason", length = 255, nullable = true, unique = false))
    })
    protected CodeFrictionEstimateType frictionEstimation;
    @XmlElement(nillable = true)
    @Embedded
    @AttributeOverrides({
        @AttributeOverride(name = "value", column = @Column(name = "frictiondevice_value", length = 255, nullable = true, unique = false)),
        @AttributeOverride(name = "nilReason", column = @Column(name = "frictiondevice_nilreason", length = 255, nullable = true, unique = false))
    })
    protected CodeFrictionDeviceType frictionDevice;
    @XmlElement(nillable = true)
    @Embedded
    @AttributeOverrides({
        @AttributeOverride(name = "value", column = @Column(name = "obscuredlights_value", length = 255, nullable = true, unique = false)),
        @AttributeOverride(name = "nilReason", column = @Column(name = "obscuredlights_nilreason", length = 255, nullable = true, unique = false))
    })
    protected CodeYesNoType obscuredLights;
    @XmlElement(nillable = true)
    @Embedded
    @AttributeOverrides({
        @AttributeOverride(name = "value", column = @Column(name = "furtherclearancetime_value", length = 255, columnDefinition = "TEXT", nullable = true, unique = false)),
        @AttributeOverride(name = "nilReason", column = @Column(name = "furtherclearancetime_nilreason", length = 255, nullable = true, unique = false))
    })
    protected TimeType furtherClearanceTime;
    @XmlElement(nillable = true)
    @Embedded
    @AttributeOverrides({
        @AttributeOverride(name = "value", column = @Column(name = "furthertotalclearance_value", length = 255, nullable = true, unique = false)),
        @AttributeOverride(name = "nilReason", column = @Column(name = "furthertotalclearance_nilreason", length = 255, nullable = true, unique = false))
    })
    protected CodeYesNoType furtherTotalClearance;
    @XmlElement(nillable = true)
    @Embedded
    @AttributeOverrides({
        @AttributeOverride(name = "value", column = @Column(name = "proportion_value", length = 255, columnDefinition = "DECIMAL", nullable = true, unique = false)),
        @AttributeOverride(name = "nilReason", column = @Column(name = "proportion_nilreason", length = 255, nullable = true, unique = false))
    })
    protected ValPercentType proportion;
    @XmlElement(nillable = true)
    @OneToMany(cascade = {
        CascadeType.ALL
    }, fetch = FetchType.EAGER)
    @JoinTable(name = "master_join", joinColumns = {
        @JoinColumn(name = "source_id")
    }, inverseJoinColumns = {
        @JoinColumn(name = "target_id")
    })
    protected List<RidgePropertyType> criticalRidge;
    @XmlElement(nillable = true)
    @OneToMany(cascade = {
        CascadeType.ALL
    }, fetch = FetchType.EAGER)
    @JoinTable(name = "master_join", joinColumns = {
        @JoinColumn(name = "source_id")
    }, inverseJoinColumns = {
        @JoinColumn(name = "target_id")
    })
    protected List<SurfaceContaminationLayerPropertyType> layer;
    @XmlElement(nillable = true)
    @OneToMany(cascade = {
        CascadeType.ALL
    }, fetch = FetchType.EAGER)
    @JoinTable(name = "master_join", joinColumns = {
        @JoinColumn(name = "source_id")
    }, inverseJoinColumns = {
        @JoinColumn(name = "target_id")
    })
    protected List<NotePropertyType> annotation;
    @XmlElement(nillable = true)
    @Embedded
    @AttributeOverrides({
        @AttributeOverride(name = "value", column = @Column(name = "clearedlength_value", length = 255, columnDefinition = "DECIMAL", nullable = true, unique = false)),
        @AttributeOverride(name = "uom", column = @Column(name = "clearedlength_uom", length = 255, nullable = true, unique = false)),
        @AttributeOverride(name = "nilReason", column = @Column(name = "clearedlength_nilreason", length = 255, nullable = true, unique = false))
    })
    protected ValDistanceType clearedLength;
    @XmlElement(nillable = true)
    @Embedded
    @AttributeOverrides({
        @AttributeOverride(name = "value", column = @Column(name = "clearedwidth_value", length = 255, columnDefinition = "DECIMAL", nullable = true, unique = false)),
        @AttributeOverride(name = "uom", column = @Column(name = "clearedwidth_uom", length = 255, nullable = true, unique = false)),
        @AttributeOverride(name = "nilReason", column = @Column(name = "clearedwidth_nilreason", length = 255, nullable = true, unique = false))
    })
    protected ValDistanceType clearedWidth;
    @XmlElement(nillable = true)
    @Embedded
    @AttributeOverrides({
        @AttributeOverride(name = "value", column = @Column(name = "clearedside_value", length = 255, nullable = true, unique = false)),
        @AttributeOverride(name = "nilReason", column = @Column(name = "clearedside_nilreason", length = 255, nullable = true, unique = false))
    })
    protected CodeSideType clearedSide;
    @XmlElement(nillable = true)
    @Embedded
    @AttributeOverrides({
        @AttributeOverride(name = "value", column = @Column(name = "furtherclearancelength_value", length = 255, columnDefinition = "DECIMAL", nullable = true, unique = false)),
        @AttributeOverride(name = "uom", column = @Column(name = "furtherclearancelength_uom", length = 255, nullable = true, unique = false)),
        @AttributeOverride(name = "nilReason", column = @Column(name = "furtherclearancelength_nilreason", length = 255, nullable = true, unique = false))
    })
    protected ValDistanceType furtherClearanceLength;
    @XmlElement(nillable = true)
    @Embedded
    @AttributeOverrides({
        @AttributeOverride(name = "value", column = @Column(name = "furtherclearancewidth_value", length = 255, columnDefinition = "DECIMAL", nullable = true, unique = false)),
        @AttributeOverride(name = "uom", column = @Column(name = "furtherclearancewidth_uom", length = 255, nullable = true, unique = false)),
        @AttributeOverride(name = "nilReason", column = @Column(name = "furtherclearancewidth_nilreason", length = 255, nullable = true, unique = false))
    })
    protected ValDistanceType furtherClearanceWidth;
    @XmlElement(nillable = true)
    @Embedded
    @AttributeOverrides({
        @AttributeOverride(name = "value", column = @Column(name = "obscuredlightsside_value", length = 255, nullable = true, unique = false)),
        @AttributeOverride(name = "nilReason", column = @Column(name = "obscuredlightsside_nilreason", length = 255, nullable = true, unique = false))
    })
    protected CodeSideType obscuredLightsSide;
    @XmlElement(nillable = true)
    @Embedded
    @AttributeOverrides({
        @AttributeOverride(name = "value", column = @Column(name = "clearedlengthbegin_value", length = 255, columnDefinition = "DECIMAL", nullable = true, unique = false)),
        @AttributeOverride(name = "uom", column = @Column(name = "clearedlengthbegin_uom", length = 255, nullable = true, unique = false)),
        @AttributeOverride(name = "nilReason", column = @Column(name = "clearedlengthbegin_nilreason", length = 255, nullable = true, unique = false))
    })
    protected ValDistanceType clearedLengthBegin;
    @XmlElement(nillable = true)
    @Embedded
    @AttributeOverrides({
        @AttributeOverride(name = "value", column = @Column(name = "taxiwayavailable_value", length = 255, nullable = true, unique = false)),
        @AttributeOverride(name = "nilReason", column = @Column(name = "taxiwayavailable_nilreason", length = 255, nullable = true, unique = false))
    })
    protected CodeYesNoType taxiwayAvailable;
    @XmlElement(nillable = true)
    @Embedded
    @AttributeOverrides({
        @AttributeOverride(name = "value", column = @Column(name = "apronavailable_value", length = 255, nullable = true, unique = false)),
        @AttributeOverride(name = "nilReason", column = @Column(name = "apronavailable_nilreason", length = 255, nullable = true, unique = false))
    })
    protected CodeYesNoType apronAvailable;
    @Transient
    protected List<RunwayContaminationType.Extension> extension;

    /**
     * aixm:DateTimeType
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObservationTime() {
        return observationTime;
    }

    /**
     * Sets the value of the observationTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getObservationTime()
     */
    public void setObservationTime(String value) {
        this.observationTime = value;
    }

    public boolean isSetObservationTime() {
        return (this.observationTime!= null);
    }

    /**
     * aixm:DateTimeType
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNextObservationTime() {
        return nextObservationTime;
    }

    /**
     * Sets the value of the nextObservationTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getNextObservationTime()
     */
    public void setNextObservationTime(String value) {
        this.nextObservationTime = value;
    }

    public boolean isSetNextObservationTime() {
        return (this.nextObservationTime!= null);
    }

    /**
     * Gets the value of the depth property.
     * 
     * @return
     *     possible object is
     *     {@link ValDepthType }
     *     
     */
    public ValDepthType getDepth() {
        return depth;
    }

    /**
     * Sets the value of the depth property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValDepthType }
     *     
     */
    public void setDepth(ValDepthType value) {
        this.depth = value;
    }

    public boolean isSetDepth() {
        return (this.depth!= null);
    }

    /**
     * Gets the value of the frictionCoefficient property.
     * 
     * @return
     *     possible object is
     *     {@link ValFrictionType }
     *     
     */
    public ValFrictionType getFrictionCoefficient() {
        return frictionCoefficient;
    }

    /**
     * Sets the value of the frictionCoefficient property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValFrictionType }
     *     
     */
    public void setFrictionCoefficient(ValFrictionType value) {
        this.frictionCoefficient = value;
    }

    public boolean isSetFrictionCoefficient() {
        return (this.frictionCoefficient!= null);
    }

    /**
     * Gets the value of the frictionEstimation property.
     * 
     * @return
     *     possible object is
     *     {@link CodeFrictionEstimateType }
     *     
     */
    public CodeFrictionEstimateType getFrictionEstimation() {
        return frictionEstimation;
    }

    /**
     * Sets the value of the frictionEstimation property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeFrictionEstimateType }
     *     
     */
    public void setFrictionEstimation(CodeFrictionEstimateType value) {
        this.frictionEstimation = value;
    }

    public boolean isSetFrictionEstimation() {
        return (this.frictionEstimation!= null);
    }

    /**
     * Gets the value of the frictionDevice property.
     * 
     * @return
     *     possible object is
     *     {@link CodeFrictionDeviceType }
     *     
     */
    public CodeFrictionDeviceType getFrictionDevice() {
        return frictionDevice;
    }

    /**
     * Sets the value of the frictionDevice property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeFrictionDeviceType }
     *     
     */
    public void setFrictionDevice(CodeFrictionDeviceType value) {
        this.frictionDevice = value;
    }

    public boolean isSetFrictionDevice() {
        return (this.frictionDevice!= null);
    }

    /**
     * Gets the value of the obscuredLights property.
     * 
     * @return
     *     possible object is
     *     {@link CodeYesNoType }
     *     
     */
    public CodeYesNoType getObscuredLights() {
        return obscuredLights;
    }

    /**
     * Sets the value of the obscuredLights property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeYesNoType }
     *     
     */
    public void setObscuredLights(CodeYesNoType value) {
        this.obscuredLights = value;
    }

    public boolean isSetObscuredLights() {
        return (this.obscuredLights!= null);
    }

    /**
     * Gets the value of the furtherClearanceTime property.
     * 
     * @return
     *     possible object is
     *     {@link TimeType }
     *     
     */
    public TimeType getFurtherClearanceTime() {
        return furtherClearanceTime;
    }

    /**
     * Sets the value of the furtherClearanceTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimeType }
     *     
     */
    public void setFurtherClearanceTime(TimeType value) {
        this.furtherClearanceTime = value;
    }

    public boolean isSetFurtherClearanceTime() {
        return (this.furtherClearanceTime!= null);
    }

    /**
     * Gets the value of the furtherTotalClearance property.
     * 
     * @return
     *     possible object is
     *     {@link CodeYesNoType }
     *     
     */
    public CodeYesNoType getFurtherTotalClearance() {
        return furtherTotalClearance;
    }

    /**
     * Sets the value of the furtherTotalClearance property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeYesNoType }
     *     
     */
    public void setFurtherTotalClearance(CodeYesNoType value) {
        this.furtherTotalClearance = value;
    }

    public boolean isSetFurtherTotalClearance() {
        return (this.furtherTotalClearance!= null);
    }

    /**
     * Gets the value of the proportion property.
     * 
     * @return
     *     possible object is
     *     {@link ValPercentType }
     *     
     */
    public ValPercentType getProportion() {
        return proportion;
    }

    /**
     * Sets the value of the proportion property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValPercentType }
     *     
     */
    public void setProportion(ValPercentType value) {
        this.proportion = value;
    }

    public boolean isSetProportion() {
        return (this.proportion!= null);
    }

    /**
     * Gets the value of the criticalRidge property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the criticalRidge property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getCriticalRidge().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RidgePropertyType }
     * </p>
     * 
     * 
     * @return
     *     The value of the criticalRidge property.
     */
    public List<RidgePropertyType> getCriticalRidge() {
        if (criticalRidge == null) {
            criticalRidge = new ArrayList<>();
        }
        return this.criticalRidge;
    }

    public boolean isSetCriticalRidge() {
        return ((this.criticalRidge!= null)&&(!this.criticalRidge.isEmpty()));
    }

    public void unsetCriticalRidge() {
        this.criticalRidge = null;
    }

    /**
     * Gets the value of the layer property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the layer property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getLayer().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SurfaceContaminationLayerPropertyType }
     * </p>
     * 
     * 
     * @return
     *     The value of the layer property.
     */
    public List<SurfaceContaminationLayerPropertyType> getLayer() {
        if (layer == null) {
            layer = new ArrayList<>();
        }
        return this.layer;
    }

    public boolean isSetLayer() {
        return ((this.layer!= null)&&(!this.layer.isEmpty()));
    }

    public void unsetLayer() {
        this.layer = null;
    }

    /**
     * Gets the value of the annotation property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the annotation property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getAnnotation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NotePropertyType }
     * </p>
     * 
     * 
     * @return
     *     The value of the annotation property.
     */
    public List<NotePropertyType> getAnnotation() {
        if (annotation == null) {
            annotation = new ArrayList<>();
        }
        return this.annotation;
    }

    public boolean isSetAnnotation() {
        return ((this.annotation!= null)&&(!this.annotation.isEmpty()));
    }

    public void unsetAnnotation() {
        this.annotation = null;
    }

    /**
     * Gets the value of the clearedLength property.
     * 
     * @return
     *     possible object is
     *     {@link ValDistanceType }
     *     
     */
    public ValDistanceType getClearedLength() {
        return clearedLength;
    }

    /**
     * Sets the value of the clearedLength property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValDistanceType }
     *     
     */
    public void setClearedLength(ValDistanceType value) {
        this.clearedLength = value;
    }

    public boolean isSetClearedLength() {
        return (this.clearedLength!= null);
    }

    /**
     * Gets the value of the clearedWidth property.
     * 
     * @return
     *     possible object is
     *     {@link ValDistanceType }
     *     
     */
    public ValDistanceType getClearedWidth() {
        return clearedWidth;
    }

    /**
     * Sets the value of the clearedWidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValDistanceType }
     *     
     */
    public void setClearedWidth(ValDistanceType value) {
        this.clearedWidth = value;
    }

    public boolean isSetClearedWidth() {
        return (this.clearedWidth!= null);
    }

    /**
     * Gets the value of the clearedSide property.
     * 
     * @return
     *     possible object is
     *     {@link CodeSideType }
     *     
     */
    public CodeSideType getClearedSide() {
        return clearedSide;
    }

    /**
     * Sets the value of the clearedSide property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeSideType }
     *     
     */
    public void setClearedSide(CodeSideType value) {
        this.clearedSide = value;
    }

    public boolean isSetClearedSide() {
        return (this.clearedSide!= null);
    }

    /**
     * Gets the value of the furtherClearanceLength property.
     * 
     * @return
     *     possible object is
     *     {@link ValDistanceType }
     *     
     */
    public ValDistanceType getFurtherClearanceLength() {
        return furtherClearanceLength;
    }

    /**
     * Sets the value of the furtherClearanceLength property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValDistanceType }
     *     
     */
    public void setFurtherClearanceLength(ValDistanceType value) {
        this.furtherClearanceLength = value;
    }

    public boolean isSetFurtherClearanceLength() {
        return (this.furtherClearanceLength!= null);
    }

    /**
     * Gets the value of the furtherClearanceWidth property.
     * 
     * @return
     *     possible object is
     *     {@link ValDistanceType }
     *     
     */
    public ValDistanceType getFurtherClearanceWidth() {
        return furtherClearanceWidth;
    }

    /**
     * Sets the value of the furtherClearanceWidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValDistanceType }
     *     
     */
    public void setFurtherClearanceWidth(ValDistanceType value) {
        this.furtherClearanceWidth = value;
    }

    public boolean isSetFurtherClearanceWidth() {
        return (this.furtherClearanceWidth!= null);
    }

    /**
     * Gets the value of the obscuredLightsSide property.
     * 
     * @return
     *     possible object is
     *     {@link CodeSideType }
     *     
     */
    public CodeSideType getObscuredLightsSide() {
        return obscuredLightsSide;
    }

    /**
     * Sets the value of the obscuredLightsSide property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeSideType }
     *     
     */
    public void setObscuredLightsSide(CodeSideType value) {
        this.obscuredLightsSide = value;
    }

    public boolean isSetObscuredLightsSide() {
        return (this.obscuredLightsSide!= null);
    }

    /**
     * Gets the value of the clearedLengthBegin property.
     * 
     * @return
     *     possible object is
     *     {@link ValDistanceType }
     *     
     */
    public ValDistanceType getClearedLengthBegin() {
        return clearedLengthBegin;
    }

    /**
     * Sets the value of the clearedLengthBegin property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValDistanceType }
     *     
     */
    public void setClearedLengthBegin(ValDistanceType value) {
        this.clearedLengthBegin = value;
    }

    public boolean isSetClearedLengthBegin() {
        return (this.clearedLengthBegin!= null);
    }

    /**
     * Gets the value of the taxiwayAvailable property.
     * 
     * @return
     *     possible object is
     *     {@link CodeYesNoType }
     *     
     */
    public CodeYesNoType getTaxiwayAvailable() {
        return taxiwayAvailable;
    }

    /**
     * Sets the value of the taxiwayAvailable property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeYesNoType }
     *     
     */
    public void setTaxiwayAvailable(CodeYesNoType value) {
        this.taxiwayAvailable = value;
    }

    public boolean isSetTaxiwayAvailable() {
        return (this.taxiwayAvailable!= null);
    }

    /**
     * Gets the value of the apronAvailable property.
     * 
     * @return
     *     possible object is
     *     {@link CodeYesNoType }
     *     
     */
    public CodeYesNoType getApronAvailable() {
        return apronAvailable;
    }

    /**
     * Sets the value of the apronAvailable property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeYesNoType }
     *     
     */
    public void setApronAvailable(CodeYesNoType value) {
        this.apronAvailable = value;
    }

    public boolean isSetApronAvailable() {
        return (this.apronAvailable!= null);
    }

    /**
     * Gets the value of the extension property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the extension property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getExtension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RunwayContaminationType.Extension }
     * </p>
     * 
     * 
     * @return
     *     The value of the extension property.
     */
    public List<RunwayContaminationType.Extension> getExtension() {
        if (extension == null) {
            extension = new ArrayList<>();
        }
        return this.extension;
    }

    public boolean isSetExtension() {
        return ((this.extension!= null)&&(!this.extension.isEmpty()));
    }

    public void unsetExtension() {
        this.extension = null;
    }


    /**
     * <p>Java class for anonymous complex type</p>.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.</p>
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       <choice>
     *         <element ref="{http://www.aixm.aero/schema/5.1.1}AbstractSurfaceContaminationExtension"/>
     *         <element ref="{http://www.aixm.aero/schema/5.1.1}AbstractRunwayContaminationExtension"/>
     *       </choice>
     *       <attGroup ref="{http://www.opengis.net/gml/3.2}OwnershipAttributeGroup"/>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "abstractSurfaceContaminationExtension",
        "abstractRunwayContaminationExtension"
    })
    public static class Extension {

        @XmlElement(name = "AbstractSurfaceContaminationExtension")
        @OneToOne(cascade = {
            CascadeType.ALL
        }, fetch = FetchType.EAGER)
        @JoinColumn(name = "abstractsurfacecontaminationextension_id", referencedColumnName = "id")
        protected AbstractExtensionType abstractSurfaceContaminationExtension;
        @XmlElement(name = "AbstractRunwayContaminationExtension")
        @OneToOne(cascade = {
            CascadeType.ALL
        }, fetch = FetchType.EAGER)
        @JoinColumn(name = "abstractrunwaycontaminationextension_id", referencedColumnName = "id")
        protected AbstractExtensionType abstractRunwayContaminationExtension;
        @XmlAttribute(name = "owns")
        @Transient
        protected Boolean owns;

        /**
         * Gets the value of the abstractSurfaceContaminationExtension property.
         * 
         * @return
         *     possible object is
         *     {@link AbstractExtensionType }
         *     
         */
        public AbstractExtensionType getAbstractSurfaceContaminationExtension() {
            return abstractSurfaceContaminationExtension;
        }

        /**
         * Sets the value of the abstractSurfaceContaminationExtension property.
         * 
         * @param value
         *     allowed object is
         *     {@link AbstractExtensionType }
         *     
         */
        public void setAbstractSurfaceContaminationExtension(AbstractExtensionType value) {
            this.abstractSurfaceContaminationExtension = value;
        }

        public boolean isSetAbstractSurfaceContaminationExtension() {
            return (this.abstractSurfaceContaminationExtension!= null);
        }

        /**
         * Gets the value of the abstractRunwayContaminationExtension property.
         * 
         * @return
         *     possible object is
         *     {@link AbstractExtensionType }
         *     
         */
        public AbstractExtensionType getAbstractRunwayContaminationExtension() {
            return abstractRunwayContaminationExtension;
        }

        /**
         * Sets the value of the abstractRunwayContaminationExtension property.
         * 
         * @param value
         *     allowed object is
         *     {@link AbstractExtensionType }
         *     
         */
        public void setAbstractRunwayContaminationExtension(AbstractExtensionType value) {
            this.abstractRunwayContaminationExtension = value;
        }

        public boolean isSetAbstractRunwayContaminationExtension() {
            return (this.abstractRunwayContaminationExtension!= null);
        }

        /**
         * Gets the value of the owns property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public boolean isOwns() {
            if (owns == null) {
                return false;
            } else {
                return owns;
            }
        }

        /**
         * Sets the value of the owns property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setOwns(boolean value) {
            this.owns = value;
        }

        public boolean isSetOwns() {
            return (this.owns!= null);
        }

        public void unsetOwns() {
            this.owns = null;
        }

    }

}
