//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.aixm.delorean.core.schema.a5_1.aixm;

import com.aixm.delorean.core.adapter.a5_1.gis.CurveTypeAdapter;
import com.aixm.delorean.core.adapter.type.gis.AixmCurveType;
import jakarta.persistence.Embedded;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for CurvePropertyType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="CurvePropertyType">
 *   <complexContent>
 *     <extension base="{http://www.aixm.aero/schema/5.1}AbstractAIXMPropertyType">
 *       <sequence>
 *         <element name="curve" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CurvePropertyType", propOrder = {
    "curve"
})
@Entity
@Table(name = "curve", schema = "public")
public class CurvePropertyType
    extends AbstractAIXMPropertyType
{

    @XmlElement(required = true, type = CurveType.class, name = "Curve")
    @XmlJavaTypeAdapter(CurveTypeAdapter.class)
    @Embedded
    protected AixmCurveType curve;

    /**
     * Gets the value of the curve property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public AixmCurveType getCurve() {
        return curve;
    }

    /**
     * Sets the value of the curve property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurve(AixmCurveType value) {
        this.curve = value;
    }

    public boolean isSetCurve() {
        return (this.curve!= null);
    }

}
