import Machinery

config = {
    "ignore": [
        "AIXMBasicMessageType",
        "BasicMessageMemberAIXMPropertyType",
        "AerialRefuellingPropertyType",
        "AerialRefuellingAnchorPropertyType",
        "AerialRefuellingPointPropertyType",
        "AerialRefuellingTrackPropertyType",
        "AuthorityForAerialRefuellingPropertyType",
        "AirportHeliportPropertyType",
        "AirportHeliportAvailabilityPropertyType",
        "AirportHeliportCollocationPropertyType",
        "AirportHeliportProtectionAreaPropertyType",
        "AirportHeliportResponsibilityOrganisationPropertyType",
        "AirportHeliportUsagePropertyType",
        "AirportHotSpotPropertyType",
        "AltimeterSourcePropertyType",
        "AltimeterSourceStatusPropertyType",
        "CityPropertyType",
        "ConditionCombinationPropertyType",
        "NonMovementAreaPropertyType",
        "SurfaceCharacteristicsPropertyType",
        "SurveyControlPointPropertyType",
        "UsageConditionPropertyType",
        "WorkAreaPropertyType",
        "WorkareaActivityPropertyType",
        "AircraftStandPropertyType",
        "ApronPropertyType",
        "ApronAreaAvailabilityPropertyType",
        "ApronAreaUsagePropertyType",
        "ApronElementPropertyType",
        "DeicingAreaPropertyType",
        "PassengerLoadingBridgePropertyType",
        "RoadPropertyType",
        "TouchDownLiftOffPropertyType",
        "TouchDownLiftOffSafeAreaPropertyType",
        "ApproachLightingSystemPropertyType",
        "ApronLightSystemPropertyType",
        "GroundLightingAvailabilityPropertyType",
        "GroundLightSystemPropertyType",
        "GuidanceLineLightSystemPropertyType",
        "LightActivationPropertyType",
        "RunwayDirectionLightSystemPropertyType",
        "RunwayProtectAreaLightSystemPropertyType",
        "TaxiHoldingPositionLightSystemPropertyType",
        "TaxiwayLightSystemPropertyType",
        "TouchDownLiftOffLightSystemPropertyType",
        "AirportProtectionAreaMarkingPropertyType",
        "ApronMarkingPropertyType",
        "DeicingAreaMarkingPropertyType",
        "GuidanceLineMarkingPropertyType",
        "MarkingPropertyType",
        "MarkingElementPropertyType",
        "RunwayMarkingPropertyType",
        "StandMarkingPropertyType",
        "TaxiHoldingPositionMarkingPropertyType",
        "TaxiwayMarkingPropertyType",
        "TouchDownLiftOffMarkingPropertyType",
        "ArrestingGearPropertyType",
        "ManoeuvringAreaAvailabilityPropertyType",
        "ManoeuvringAreaUsagePropertyType",
        "NavaidEquipmentDistancePropertyType",
        "RunwayPropertyType",
        "RunwayBlastPadPropertyType",
        "RunwayCentrelinePointPropertyType",
        "RunwayDeclaredDistancePropertyType",
        "RunwayDeclaredDistanceValuePropertyType",
        "RunwayDirectionPropertyType",
        "RunwayElementPropertyType",
        "RunwayProtectAreaPropertyType",
        "RunwayVisualRangePropertyType",
        "VisualGlideSlopeIndicatorPropertyType",
        "FloatingDockSitePropertyType",
        "MarkingBuoyPropertyType",
        "SeaplaneLandingAreaPropertyType",
        "SeaplaneRampSitePropertyType",
        "AircraftStandContaminationPropertyType",
        "AirportHeliportContaminationPropertyType",
        "ApronContaminationPropertyType",
        "RidgePropertyType",
        "RunwayContaminationPropertyType",
        "RunwaySectionContaminationPropertyType",
        "SurfaceContaminationPropertyType",
        "SurfaceContaminationLayerPropertyType",
        "TaxiwayContaminationPropertyType",
        "TouchDownLiftOffContaminationPropertyType",
        "GuidanceLinePropertyType",
        "TaxiHoldingPositionPropertyType",
        "TaxiwayPropertyType",
        "TaxiwayElementPropertyType",
        "AirspacePropertyType",
        "AirspaceActivationPropertyType",
        "AirspaceGeometryComponentPropertyType",
        "AirspaceLayerClassPropertyType",
        "AirspaceVolumePropertyType",
        "AirspaceVolumeDependencyPropertyType",
        "AuthorityForAirspacePropertyType",
        "GeoBorderPropertyType",
        "CurvePropertyType",
        "ElevatedCurvePropertyType",
        "ElevatedPointPropertyType",
        "ElevatedSurfacePropertyType",
        "PointPropertyType",
        "SurfacePropertyType",
        "HoldingPatternPropertyType",
        "HoldingPatternDistancePropertyType",
        "HoldingPatternDurationPropertyType",
        "UnplannedHoldingPropertyType",
        "AuthorityForNavaidEquipmentPropertyType",
        "AuthorityForSpecialNavigationStationPropertyType",
        "AuthorityForSpecialNavigationSystemPropertyType",
        "AzimuthPropertyType",
        "CheckpointINSPropertyType",
        "CheckpointVORPropertyType",
        "DirectionFinderPropertyType",
        "DMEPropertyType",
        "ElevationPropertyType",
        "GlidepathPropertyType",
        "LocalizerPropertyType",
        "MarkerBeaconPropertyType",
        "NavaidPropertyType",
        "NavaidComponentPropertyType",
        "NavaidEquipmentPropertyType",
        "NavaidEquipmentMonitoringPropertyType",
        "NavaidOperationalStatusPropertyType",
        "NavigationSystemCheckpointPropertyType",
        "NDBPropertyType",
        "SDFPropertyType",
        "SpecialNavigationStationPropertyType",
        "SpecialNavigationStationStatusPropertyType",
        "SpecialNavigationSystemPropertyType",
        "TACANPropertyType",
        "VORPropertyType",
        "AngleIndicationPropertyType",
        "AngleUsePropertyType",
        "DistanceIndicationPropertyType",
        "EnRouteSegmentPointPropertyType",
        "PointReferencePropertyType",
        "SegmentPointPropertyType",
        "TerminalSegmentPointPropertyType",
        "DesignatedPointPropertyType",
        "SignificantPointInAirspacePropertyType",
        "AeronauticalGroundLightPropertyType",
        "LinguisticNotePropertyType",
        "NotePropertyType",
        "ObstacleAreaPropertyType",
        "VerticalStructurePropertyType",
        "VerticalStructureLightingStatusPropertyType",
        "VerticalStructurePartPropertyType",
        "OrganisationAuthorityPropertyType",
        "OrganisationAuthorityAssociationPropertyType",
        "UnitPropertyType",
        "UnitAvailabilityPropertyType",
        "UnitDependencyPropertyType",
        "ApproachAltitudeTablePropertyType",
        "ApproachConditionPropertyType",
        "ApproachDistanceTablePropertyType",
        "ApproachTimingTablePropertyType",
        "FinalProfilePropertyType",
        "InstrumentApproachProcedurePropertyType",
        "MissedApproachGroupPropertyType",
        "TerminalArrivalAreaPropertyType",
        "TerminalArrivalAreaSectorPropertyType",
        "FASDataBlockPropertyType",
        "CirclingAreaPropertyType",
        "CirclingRestrictionPropertyType",
        "EquipmentUnavailableAdjustmentPropertyType",
        "EquipmentUnavailableAdjustmentColumnPropertyType",
        "MinimaPropertyType",
        "StandardInstrumentArrivalPropertyType",
        "DepartureArrivalConditionPropertyType",
        "NavigationAreaPropertyType",
        "NavigationAreaSectorPropertyType",
        "SectorDesignPropertyType",
        "StandardInstrumentDeparturePropertyType",
        "SafeAltitudeAreaPropertyType",
        "SafeAltitudeAreaSectorPropertyType",
        "ApproachLegPropertyType",
        "ArrivalFeederLegPropertyType",
        "ArrivalLegPropertyType",
        "DepartureLegPropertyType",
        "FinalLegPropertyType",
        "HoldingUsePropertyType",
        "InitialLegPropertyType",
        "IntermediateLegPropertyType",
        "LandingTakeoffAreaCollectionPropertyType",
        "MissedApproachLegPropertyType",
        "NavigationAreaRestrictionPropertyType",
        "ProcedurePropertyType",
        "ProcedureDMEPropertyType",
        "ProcedureTransitionPropertyType",
        "ProcedureTransitionLegPropertyType",
        "SegmentLegPropertyType",
        "ProcedureAvailabilityPropertyType",
        "ChangeOverPointPropertyType",
        "RoutePropertyType",
        "RouteAvailabilityPropertyType",
        "RouteDMEPropertyType",
        "RoutePortionPropertyType",
        "RouteSegmentPropertyType",
        "AirspaceBorderCrossingPropertyType",
        "DirectFlightPropertyType",
        "DirectFlightClassPropertyType",
        "DirectFlightSegmentPropertyType",
        "FlightConditionCircumstancePropertyType",
        "FlightConditionCombinationPropertyType",
        "FlightConditionElementPropertyType",
        "FlightRestrictionPropertyType",
        "FlightRestrictionLevelPropertyType",
        "FlightRestrictionRoutePropertyType",
        "FlightRoutingElementPropertyType",
        "RulesProceduresPropertyType",
        "AircraftGroundServicePropertyType",
        "AirportClearanceServicePropertyType",
        "AirportGroundServicePropertyType",
        "AirportSuppliesServicePropertyType",
        "AirTrafficControlServicePropertyType",
        "AirTrafficManagementServicePropertyType",
        "CallsignDetailPropertyType",
        "FireFightingServicePropertyType",
        "FuelPropertyType",
        "GroundTrafficControlServicePropertyType",
        "InformationServicePropertyType",
        "NitrogenPropertyType",
        "OilPropertyType",
        "OxygenPropertyType",
        "PassengerServicePropertyType",
        "PilotControlledLightingPropertyType",
        "RadioCommunicationChannelPropertyType",
        "RadioCommunicationOperationalStatusPropertyType",
        "SearchRescueServicePropertyType",
        "ServicePropertyType",
        "ServiceOperationalStatusPropertyType",
        "TrafficSeparationServicePropertyType",
        "ContactInformationPropertyType",
        "OnlineContactPropertyType",
        "PostalAddressPropertyType",
        "TelephoneContactPropertyType",
        "AircraftCharacteristicPropertyType",
        "FlightCharacteristicPropertyType",
        "AirspaceLayerPropertyType",
        "CircleSectorPropertyType",
        "LightElementPropertyType",
        "LightElementStatusPropertyType",
        "MeteorologyPropertyType",
        "RadioFrequencyAreaPropertyType",
        "PropertiesWithSchedulePropertyType",
        "SpecialDatePropertyType",
        "TimesheetPropertyType",
        "StandardLevelPropertyType",
        "StandardLevelColumnPropertyType",
        "StandardLevelSectorPropertyType",
        "StandardLevelTablePropertyType",
        "AltitudeAdjustmentPropertyType",
        "HoldingAssessmentPropertyType",
        "ObstacleAssessmentAreaPropertyType",
        "ObstaclePlacementPropertyType",
        "ObstructionPropertyType",
        "PrecisionApproachRadarPropertyType",
        "PrimarySurveillanceRadarPropertyType",
        "RadarComponentPropertyType",
        "RadarEquipmentPropertyType",
        "RadarSystemPropertyType",
        "ReflectorPropertyType",
        "SecondarySurveillanceRadarPropertyType",
        "SurveillanceGroundStationPropertyType",
        "SurveillanceRadarPropertyType",
        "AbstractAIXMPropertyType",
        "FeatureMetadataPropertyType",
        "MessageMetadataPropertyType",
               ],
    "transient" : [],
    "embed": [],
    "abstract": [],
    "constraint_methode": "xjb",
    "package": "com.aixm.delorean.core.schema.a5_1_1.aixm",
    "output_path": "util/test_aixm.xjb"
}

feature = {
    "name" : "AIXM_Features",
    "path" : "src/main/resources/a5_1_1/AIXM_Features.xsd",
    "strategy" : Machinery.strategy.feature,
    "package" : "com.aixm.delorean.core.schema.a5_1_1.aixm.feature",
    "manual" : "util/manual/AIXM_Features.xjb"
}

data_types = {
    "name" : "AIXM_DataTypes",
    "path" : "src/main/resources/a5_1_1/AIXM_DataTypes.xsd",
    "strategy" : Machinery.strategy.data_type,
    "manual" : "util/manual/AIXM_DataTypes.xjb"
}

abstract = {
    "name" : "AIXM_AbstractGML_ObjectTypes",
    "path" : "src/main/resources/a5_1_1/AIXM_AbstractGML_ObjectTypes.xsd",
    "strategy" : Machinery.strategy.abstract,
    "manual" : "util/manual/AIXM_AbstractGML_ObjectTypes.xjb"
}

message = {
    "name" : "AIXM_BasicMessage",
    "path" : "src/main/resources/a5_1_1/AIXM_BasicMessage.xsd",
    "strategy" : Machinery.strategy.other,
    "package" : "com.aixm.delorean.core.schema.a5_1_1.aixm.message",
    "manual" : "util/manual/AIXM_BasicMessage.xjb"
}

machinery = Machinery.runner(config, [data_types, feature, abstract, message])
# machinery = Machinery.runner(config, [message])