import Machinery

config = {
    "ignore": [
        "AIXMBasicMessageType",
        "AIXMBasicMessagePropertyGroup",
        "BasicMessageMemberAIXMPropertyType",
        "AbstractAIXMMessageBaseType",
        "AbstractAIXMMessageType",
        "AbstractAIXMFeatureBaseType",
        "AbstractAIXMFeatureType",
        "AbstractAIXMTimeSliceBaseType",
        "AbstractAIXMTimeSliceType",
        "AbstractAIXMPropertyType",
        "AbstractAIXMObjectBaseType",
        "AbstractAIXMObjectType",
        "PointPropertyType",
        "CurvePropertyType",
        "SurfacePropertyType",
        "ElevatedPointPropertyType",
        "ElevatedCurvePropertyType",
        "ElevatedSurfacePropertyType",
        "MessageMetadataPropertyType",
        "FeatureMetadataPropertyType",
        "FeatureTimeSliceMetadataPropertyType",
        "MessageMetadataPropertyType,",
        "AerialRefuellingPropertyType",
        "AirportHeliportPropertyType",
        "AirportHeliportCollocationPropertyType",
        "AirportHeliportProtectionAreaPropertyType",
        "AirportHotSpotPropertyType",
        "AltimeterSourcePropertyType",
        "NonMovementAreaPropertyType",
        "SurveyControlPointPropertyType",
        "WorkAreaPropertyType",
        "AircraftStandPropertyType",
        "ApronPropertyType",
        "ApronElementPropertyType",
        "DeicingAreaPropertyType",
        "PassengerLoadingBridgePropertyType",
        "RoadPropertyType",
        "TouchDownLiftOffPropertyType",
        "TouchDownLiftOffSafeAreaPropertyType",
        "ApproachLightingSystemPropertyType",
        "ApronLightSystemPropertyType",
        "GroundLightSystemPropertyType",
        "GuidanceLineLightSystemPropertyType",
        "RunwayDirectionLightSystemPropertyType",
        "RunwayProtectAreaLightSystemPropertyType",
        "TaxiHoldingPositionLightSystemPropertyType",
        "TaxiwayLightSystemPropertyType",
        "TouchDownLiftOffLightSystemPropertyType",
        "AirportProtectionAreaMarkingPropertyType",
        "ApronMarkingPropertyType",
        "DeicingAreaMarkingPropertyType",
        "GuidanceLineMarkingPropertyType",
        "MarkingPropertyType",
        "RunwayMarkingPropertyType",
        "StandMarkingPropertyType",
        "TaxiHoldingPositionMarkingPropertyType",
        "TaxiwayMarkingPropertyType",
        "TouchDownLiftOffMarkingPropertyType",
        "ArrestingGearPropertyType",
        "RunwayPropertyType",
        "RunwayBlastPadPropertyType",
        "RunwayCentrelinePointPropertyType",
        "RunwayDirectionPropertyType",
        "RunwayElementPropertyType",
        "RunwayProtectAreaPropertyType",
        "RunwayVisualRangePropertyType",
        "VisualGlideSlopeIndicatorPropertyType",
        "FloatingDockSitePropertyType",
        "MarkingBuoyPropertyType",
        "SeaplaneLandingAreaPropertyType",
        "SeaplaneRampSitePropertyType",
        "GuidanceLinePropertyType",
        "TaxiHoldingPositionPropertyType",
        "TaxiwayPropertyType",
        "TaxiwayElementPropertyType",
        "AirspacePropertyType",
        "AuthorityForAirspacePropertyType",
        "GeoBorderPropertyType",
        "HoldingPatternPropertyType",
        "UnplannedHoldingPropertyType",
        "AzimuthPropertyType",
        "CheckpointINSPropertyType",
        "CheckpointVORPropertyType",
        "DirectionFinderPropertyType",
        "DMEPropertyType",
        "ElevationPropertyType",
        "GlidepathPropertyType",
        "LocalizerPropertyType",
        "MarkerBeaconPropertyType",
        "NavaidPropertyType",
        "NavaidEquipmentPropertyType",
        "NavigationSystemCheckpointPropertyType",
        "NDBPropertyType",
        "SDFPropertyType",
        "SpecialNavigationStationPropertyType",
        "SpecialNavigationSystemPropertyType",
        "TACANPropertyType",
        "VORPropertyType",
        "AngleIndicationPropertyType",
        "DistanceIndicationPropertyType",
        "DesignatedPointPropertyType",
        "SignificantPointInAirspacePropertyType",
        "AeronauticalGroundLightPropertyType",
        "ObstacleAreaPropertyType",
        "VerticalStructurePropertyType",
        "OrganisationAuthorityPropertyType",
        "UnitPropertyType",
        "InstrumentApproachProcedurePropertyType",
        "TerminalArrivalAreaPropertyType",
        "CirclingAreaPropertyType",
        "StandardInstrumentArrivalPropertyType",
        "NavigationAreaPropertyType",
        "StandardInstrumentDeparturePropertyType",
        "SafeAltitudeAreaPropertyType",
        "ApproachLegPropertyType",
        "ArrivalFeederLegPropertyType",
        "ArrivalLegPropertyType",
        "DepartureLegPropertyType",
        "FinalLegPropertyType",
        "InitialLegPropertyType",
        "IntermediateLegPropertyType",
        "MissedApproachLegPropertyType",
        "NavigationAreaRestrictionPropertyType",
        "ProcedurePropertyType",
        "ProcedureDMEPropertyType",
        "SegmentLegPropertyType",
        "ChangeOverPointPropertyType",
        "RoutePropertyType",
        "RouteDMEPropertyType",
        "RouteSegmentPropertyType",
        "AirspaceBorderCrossingPropertyType",
        "FlightRestrictionPropertyType",
        "RulesProceduresPropertyType",
        "AircraftGroundServicePropertyType",
        "AirportClearanceServicePropertyType",
        "AirportGroundServicePropertyType",
        "AirportSuppliesServicePropertyType",
        "AirTrafficControlServicePropertyType",
        "AirTrafficManagementServicePropertyType",
        "FireFightingServicePropertyType",
        "GroundTrafficControlServicePropertyType",
        "InformationServicePropertyType",
        "PassengerServicePropertyType",
        "PilotControlledLightingPropertyType",
        "RadioCommunicationChannelPropertyType",
        "SearchRescueServicePropertyType",
        "ServicePropertyType",
        "TrafficSeparationServicePropertyType",
        "RadioFrequencyAreaPropertyType",
        "SpecialDatePropertyType",
        "StandardLevelColumnPropertyType",
        "StandardLevelSectorPropertyType",
        "StandardLevelTablePropertyType",
        "HoldingAssessmentPropertyType",
        "PrecisionApproachRadarPropertyType",
        "PrimarySurveillanceRadarPropertyType",
        "RadarEquipmentPropertyType",
        "RadarSystemPropertyType",
        "SecondarySurveillanceRadarPropertyType",   
        "SurveillanceRadarPropertyType",
    ],
    "transient" : [
        "XHTMLType",
        "aixm:AbstractDirectFlight",
        "aixm:AbstractPropertiesWithSchedule",
        "aixm:AbstractUsageConditio",
        "aixm:AbstractSurfaceContamination",
        "aixm:AbstractSegmentPoint",
        "aixm:AbstractUsageCondition",
        "extension"
    ],
    "embed": [
        "PointType",
        "ElevatedPointType",
        "CurveType",
        "ElevatedCurveType",
        "SurfaceType",
        "ElevatedSurfaceType",
    ],
    "abstract": [],
    "package": "com.aixm.delorean.core.schema.a5_1_1.aixm",
    "output_path": "src/main/resources/a5_1_1/aixm.xjb"
}

feature = {
    "name" : "AIXM_Features",
    "path" : "src/main/resources/a5_1_1/AIXM_Features.xsd",
    "strategy" : Machinery.strategy.feature,
    "package" : "com.aixm.delorean.core.schema.a5_1_1.aixm",
    "manual" : "util/manual/AIXM_Features.xjb"
}

data_types = {
    "name" : "AIXM_DataTypes",
    "path" : "src/main/resources/a5_1_1/AIXM_DataTypes.xsd",
    "strategy" : Machinery.strategy.data_type,
    "manual" : "util/manual/AIXM_DataTypes.xjb"
}

abstract = {
    "name" : "AIXM_AbstractGML_ObjectTypes",
    "path" : "src/main/resources/a5_1_1/AIXM_AbstractGML_ObjectTypes.xsd",
    "strategy" : Machinery.strategy.abstract,
    "manual" : "util/manual/AIXM_AbstractGML_ObjectTypes.xjb"
}

message = {
    "name" : "AIXM_BasicMessage",
    "path" : "src/main/resources/a5_1_1/AIXM_BasicMessage.xsd",
    "strategy" : Machinery.strategy.other,
    "package" : "com.aixm.delorean.core.schema.a5_1_1.aixm.message",
    "manual" : "util/manual/AIXM_BasicMessage.xjb"
}

machinery = Machinery.runner(config, [data_types, feature, abstract, message])
# machinery = Machinery.runner(config, [data_types])