//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.aixm.delorean.core.schema.school;

import javax.xml.namespace.QName;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.aixm.delorean.core.schema.school package. 
 * <p>An ObjectFactory allows you to programmatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private static final QName _Point_QNAME = new QName("", "Point");
    private static final QName _ElevatedPoint_QNAME = new QName("", "ElevatedPoint");
    private static final QName _Curve_QNAME = new QName("", "Curve");
    private static final QName _ElevatedCurve_QNAME = new QName("", "ElevatedCurve");
    private static final QName _Surface_QNAME = new QName("", "Surface");
    private static final QName _ElevatedSurface_QNAME = new QName("", "ElevatedSurface");
    private static final QName _School_QNAME = new QName("", "school");
    private static final QName _SurfaceTypeHorizontalAccuracy_QNAME = new QName("", "horizontalAccuracy");
    private static final QName _ElevatedSurfaceTypeElevation_QNAME = new QName("", "elevation");
    private static final QName _ElevatedSurfaceTypeGeoidUndulation_QNAME = new QName("", "geoidUndulation");
    private static final QName _ElevatedSurfaceTypeVerticalDatum_QNAME = new QName("", "verticalDatum");
    private static final QName _ElevatedSurfaceTypeVerticalAccuracy_QNAME = new QName("", "verticalAccuracy");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.aixm.delorean.core.schema.school
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ElevatedSurfaceType }
     * 
     * @return
     *     the new instance of {@link ElevatedSurfaceType }
     */
    public ElevatedSurfaceType createElevatedSurfaceType() {
        return new ElevatedSurfaceType();
    }

    /**
     * Create an instance of {@link ElevatedCurveType }
     * 
     * @return
     *     the new instance of {@link ElevatedCurveType }
     */
    public ElevatedCurveType createElevatedCurveType() {
        return new ElevatedCurveType();
    }

    /**
     * Create an instance of {@link ElevatedPointType }
     * 
     * @return
     *     the new instance of {@link ElevatedPointType }
     */
    public ElevatedPointType createElevatedPointType() {
        return new ElevatedPointType();
    }

    /**
     * Create an instance of {@link PointType }
     * 
     * @return
     *     the new instance of {@link PointType }
     */
    public PointType createPointType() {
        return new PointType();
    }

    /**
     * Create an instance of {@link CurveType }
     * 
     * @return
     *     the new instance of {@link CurveType }
     */
    public CurveType createCurveType() {
        return new CurveType();
    }

    /**
     * Create an instance of {@link SurfaceType }
     * 
     * @return
     *     the new instance of {@link SurfaceType }
     */
    public SurfaceType createSurfaceType() {
        return new SurfaceType();
    }

    /**
     * Create an instance of {@link School }
     * 
     * @return
     *     the new instance of {@link School }
     */
    public School createSchool() {
        return new School();
    }

    /**
     * Create an instance of {@link Person }
     * 
     * @return
     *     the new instance of {@link Person }
     */
    public Person createPerson() {
        return new Person();
    }

    /**
     * Create an instance of {@link Teacher }
     * 
     * @return
     *     the new instance of {@link Teacher }
     */
    public Teacher createTeacher() {
        return new Teacher();
    }

    /**
     * Create an instance of {@link Student }
     * 
     * @return
     *     the new instance of {@link Student }
     */
    public Student createStudent() {
        return new Student();
    }

    /**
     * Create an instance of {@link Classroom }
     * 
     * @return
     *     the new instance of {@link Classroom }
     */
    public Classroom createClassroom() {
        return new Classroom();
    }

    /**
     * Create an instance of {@link AbstractAIXMPropertyType }
     * 
     * @return
     *     the new instance of {@link AbstractAIXMPropertyType }
     */
    public AbstractAIXMPropertyType createAbstractAIXMPropertyType() {
        return new AbstractAIXMPropertyType();
    }

    /**
     * Create an instance of {@link AixmPointPropertyType }
     * 
     * @return
     *     the new instance of {@link AixmPointPropertyType }
     */
    public AixmPointPropertyType createAixmPointPropertyType() {
        return new AixmPointPropertyType();
    }

    /**
     * Create an instance of {@link ElevatedPointPropertyType }
     * 
     * @return
     *     the new instance of {@link ElevatedPointPropertyType }
     */
    public ElevatedPointPropertyType createElevatedPointPropertyType() {
        return new ElevatedPointPropertyType();
    }

    /**
     * Create an instance of {@link AixmCurvePropertyType }
     * 
     * @return
     *     the new instance of {@link AixmCurvePropertyType }
     */
    public AixmCurvePropertyType createAixmCurvePropertyType() {
        return new AixmCurvePropertyType();
    }

    /**
     * Create an instance of {@link ElevatedCurvePropertyType }
     * 
     * @return
     *     the new instance of {@link ElevatedCurvePropertyType }
     */
    public ElevatedCurvePropertyType createElevatedCurvePropertyType() {
        return new ElevatedCurvePropertyType();
    }

    /**
     * Create an instance of {@link SurfacePropertyType }
     * 
     * @return
     *     the new instance of {@link SurfacePropertyType }
     */
    public SurfacePropertyType createSurfacePropertyType() {
        return new SurfacePropertyType();
    }

    /**
     * Create an instance of {@link ElevatedSurfacePropertyType }
     * 
     * @return
     *     the new instance of {@link ElevatedSurfacePropertyType }
     */
    public ElevatedSurfacePropertyType createElevatedSurfacePropertyType() {
        return new ElevatedSurfacePropertyType();
    }

    /**
     * Create an instance of {@link ImplementationAixmPoint }
     * 
     * @return
     *     the new instance of {@link ImplementationAixmPoint }
     */
    public ImplementationAixmPoint createImplementationAixmPoint() {
        return new ImplementationAixmPoint();
    }

    /**
     * Create an instance of {@link ImplementationAixmElevatedPoint }
     * 
     * @return
     *     the new instance of {@link ImplementationAixmElevatedPoint }
     */
    public ImplementationAixmElevatedPoint createImplementationAixmElevatedPoint() {
        return new ImplementationAixmElevatedPoint();
    }

    /**
     * Create an instance of {@link ImplementationAixmCurve }
     * 
     * @return
     *     the new instance of {@link ImplementationAixmCurve }
     */
    public ImplementationAixmCurve createImplementationAixmCurve() {
        return new ImplementationAixmCurve();
    }

    /**
     * Create an instance of {@link ImplementationAixmElevatedCurve }
     * 
     * @return
     *     the new instance of {@link ImplementationAixmElevatedCurve }
     */
    public ImplementationAixmElevatedCurve createImplementationAixmElevatedCurve() {
        return new ImplementationAixmElevatedCurve();
    }

    /**
     * Create an instance of {@link ImplementationAixmSurface }
     * 
     * @return
     *     the new instance of {@link ImplementationAixmSurface }
     */
    public ImplementationAixmSurface createImplementationAixmSurface() {
        return new ImplementationAixmSurface();
    }

    /**
     * Create an instance of {@link ImplementationAixmElevatedSurface }
     * 
     * @return
     *     the new instance of {@link ImplementationAixmElevatedSurface }
     */
    public ImplementationAixmElevatedSurface createImplementationAixmElevatedSurface() {
        return new ImplementationAixmElevatedSurface();
    }

    /**
     * Create an instance of {@link ElevatedSurfaceType.Extension }
     * 
     * @return
     *     the new instance of {@link ElevatedSurfaceType.Extension }
     */
    public ElevatedSurfaceType.Extension createElevatedSurfaceTypeExtension() {
        return new ElevatedSurfaceType.Extension();
    }

    /**
     * Create an instance of {@link ElevatedCurveType.Extension }
     * 
     * @return
     *     the new instance of {@link ElevatedCurveType.Extension }
     */
    public ElevatedCurveType.Extension createElevatedCurveTypeExtension() {
        return new ElevatedCurveType.Extension();
    }

    /**
     * Create an instance of {@link ElevatedPointType.Extension }
     * 
     * @return
     *     the new instance of {@link ElevatedPointType.Extension }
     */
    public ElevatedPointType.Extension createElevatedPointTypeExtension() {
        return new ElevatedPointType.Extension();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PointType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link PointType }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "Point", substitutionHeadNamespace = "http://www.opengis.net/gml/3.2", substitutionHeadName = "Point")
    public JAXBElement<PointType> createPoint(PointType value) {
        return new JAXBElement<>(_Point_QNAME, PointType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ElevatedPointType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ElevatedPointType }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "ElevatedPoint", substitutionHeadNamespace = "", substitutionHeadName = "Point")
    public JAXBElement<ElevatedPointType> createElevatedPoint(ElevatedPointType value) {
        return new JAXBElement<>(_ElevatedPoint_QNAME, ElevatedPointType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CurveType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CurveType }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "Curve", substitutionHeadNamespace = "http://www.opengis.net/gml/3.2", substitutionHeadName = "Curve")
    public JAXBElement<CurveType> createCurve(CurveType value) {
        return new JAXBElement<>(_Curve_QNAME, CurveType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ElevatedCurveType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ElevatedCurveType }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "ElevatedCurve", substitutionHeadNamespace = "", substitutionHeadName = "Curve")
    public JAXBElement<ElevatedCurveType> createElevatedCurve(ElevatedCurveType value) {
        return new JAXBElement<>(_ElevatedCurve_QNAME, ElevatedCurveType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SurfaceType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link SurfaceType }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "Surface", substitutionHeadNamespace = "http://www.opengis.net/gml/3.2", substitutionHeadName = "Surface")
    public JAXBElement<SurfaceType> createSurface(SurfaceType value) {
        return new JAXBElement<>(_Surface_QNAME, SurfaceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ElevatedSurfaceType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ElevatedSurfaceType }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "ElevatedSurface", substitutionHeadNamespace = "", substitutionHeadName = "Surface")
    public JAXBElement<ElevatedSurfaceType> createElevatedSurface(ElevatedSurfaceType value) {
        return new JAXBElement<>(_ElevatedSurface_QNAME, ElevatedSurfaceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link School }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link School }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "school")
    public JAXBElement<School> createSchool(School value) {
        return new JAXBElement<>(_School_QNAME, School.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Long }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "horizontalAccuracy", scope = SurfaceType.class)
    public JAXBElement<Long> createSurfaceTypeHorizontalAccuracy(Long value) {
        return new JAXBElement<>(_SurfaceTypeHorizontalAccuracy_QNAME, Long.class, SurfaceType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Long }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "elevation", scope = ElevatedSurfaceType.class)
    public JAXBElement<Long> createElevatedSurfaceTypeElevation(Long value) {
        return new JAXBElement<>(_ElevatedSurfaceTypeElevation_QNAME, Long.class, ElevatedSurfaceType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Long }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "geoidUndulation", scope = ElevatedSurfaceType.class)
    public JAXBElement<Long> createElevatedSurfaceTypeGeoidUndulation(Long value) {
        return new JAXBElement<>(_ElevatedSurfaceTypeGeoidUndulation_QNAME, Long.class, ElevatedSurfaceType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "verticalDatum", scope = ElevatedSurfaceType.class)
    public JAXBElement<String> createElevatedSurfaceTypeVerticalDatum(String value) {
        return new JAXBElement<>(_ElevatedSurfaceTypeVerticalDatum_QNAME, String.class, ElevatedSurfaceType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Long }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "verticalAccuracy", scope = ElevatedSurfaceType.class)
    public JAXBElement<Long> createElevatedSurfaceTypeVerticalAccuracy(Long value) {
        return new JAXBElement<>(_ElevatedSurfaceTypeVerticalAccuracy_QNAME, Long.class, ElevatedSurfaceType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Long }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "horizontalAccuracy", scope = CurveType.class)
    public JAXBElement<Long> createCurveTypeHorizontalAccuracy(Long value) {
        return new JAXBElement<>(_SurfaceTypeHorizontalAccuracy_QNAME, Long.class, CurveType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Long }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "elevation", scope = ElevatedCurveType.class)
    public JAXBElement<Long> createElevatedCurveTypeElevation(Long value) {
        return new JAXBElement<>(_ElevatedSurfaceTypeElevation_QNAME, Long.class, ElevatedCurveType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Long }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "geoidUndulation", scope = ElevatedCurveType.class)
    public JAXBElement<Long> createElevatedCurveTypeGeoidUndulation(Long value) {
        return new JAXBElement<>(_ElevatedSurfaceTypeGeoidUndulation_QNAME, Long.class, ElevatedCurveType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "verticalDatum", scope = ElevatedCurveType.class)
    public JAXBElement<String> createElevatedCurveTypeVerticalDatum(String value) {
        return new JAXBElement<>(_ElevatedSurfaceTypeVerticalDatum_QNAME, String.class, ElevatedCurveType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Long }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "verticalAccuracy", scope = ElevatedCurveType.class)
    public JAXBElement<Long> createElevatedCurveTypeVerticalAccuracy(Long value) {
        return new JAXBElement<>(_ElevatedSurfaceTypeVerticalAccuracy_QNAME, Long.class, ElevatedCurveType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Long }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "horizontalAccuracy", scope = PointType.class)
    public JAXBElement<Long> createPointTypeHorizontalAccuracy(Long value) {
        return new JAXBElement<>(_SurfaceTypeHorizontalAccuracy_QNAME, Long.class, PointType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Long }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "elevation", scope = ElevatedPointType.class)
    public JAXBElement<Long> createElevatedPointTypeElevation(Long value) {
        return new JAXBElement<>(_ElevatedSurfaceTypeElevation_QNAME, Long.class, ElevatedPointType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Long }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "geoidUndulation", scope = ElevatedPointType.class)
    public JAXBElement<Long> createElevatedPointTypeGeoidUndulation(Long value) {
        return new JAXBElement<>(_ElevatedSurfaceTypeGeoidUndulation_QNAME, Long.class, ElevatedPointType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "verticalDatum", scope = ElevatedPointType.class)
    public JAXBElement<String> createElevatedPointTypeVerticalDatum(String value) {
        return new JAXBElement<>(_ElevatedSurfaceTypeVerticalDatum_QNAME, String.class, ElevatedPointType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Long }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "verticalAccuracy", scope = ElevatedPointType.class)
    public JAXBElement<Long> createElevatedPointTypeVerticalAccuracy(Long value) {
        return new JAXBElement<>(_ElevatedSurfaceTypeVerticalAccuracy_QNAME, Long.class, ElevatedPointType.class, value);
    }

}
